#Use the python container image
FROM python:3.7.10

# Copy the current directory contents into the container at /app
COPY . ./

RUN apt-get update &&\
    apt-get install -y apt-utils

# install packages
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD streamlit run app.py 

