version: "2"
services:
    app:
        container_name: cryptos_app
        build: 
            dockerfile: dockerfile_app
        volumes:
            - .:/app/
            - shared-volume:/app/data
        ports:
            - "8501:8501"
        restart: always
    mycron:
        container_name: cryptos_cron
        build: 
            dockerfile: dockerfile_main
        volumes:
            - .:/app/
            - shared-volume:/app/data
        restart: always

volumes:
  shared-volume: 