#Use the python container image
FROM python:3.7.10

# Creating Working 
WORKDIR /app

COPY . ./app

RUN apt-get update && apt-get install -y \
    cron \
    build-essential \
    curl 

# install packages
RUN pip install --upgrade pip
RUN pip install -r app/requirements.txt

EXPOSE 8501

HEALTHCHECK CMD curl --fail http://localhost:8501/_stcore/health

ENTRYPOINT ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]