resources:
    base_path : C:\Users\de larrard alexandre\OneDrive - The Boston Consulting Group, Inc\Documents\repos_github\PEA
    data: data/crypto

cryptos_desc:
    Cryptos: ["BTC", "ETH", "XRP", "ADA", "DOGE", "SOL", "MATIC", "DOT", "LTC", "TRX", "XLM", "STX"]
    URL_BASE: https://www.cryptodatadownload.com/cdd/Binance_
    URL_END: USDT_1h.csv