regression_model:
    TARGET: "BINARY_TARGET_BTC"
    FEATURES:
        - "TRADECOUNT_BTC"
        - "MEAN_7_BTC"
        # - "MEDIAN-14"
        - "D-1_BTC"
        - "D-2_BTC"
        - "D-7_BTC"
        - "D-14_BTC"
        # - "WEEK_DAY"
        - "STD-7_BTC"
        - "STD-14_BTC"
        - "MIN-7_BTC"
        - "AVG_INCREMENTALS-7_BTC"
    categorical_features:
        # - "WEEK_DAY"
    WEIGHT: "WEIGHT_BTC"
    rolling : 7
    seed: 5432
    n_splits: 5
    parameters:
        objective: "binary"
        metric: "binary_logloss"
        eval_metric : "auc"
        max_depth: 6
        min_data_in_leaf: 10
        colsample_bytree: 0.75
        subsample: 0.75
        learning_rate: 0.004
        num_iterations: 1000
        # lambda_l1 : 1
        n_jobs: 7
        verbose_eval : -1
        verbose : -1
        early_stopping_round: 50