resources:
    base_path : ./
    data: data/crypto
    log_path : ./logs

cryptos_desc:
    Cryptos: ["BTC", "ETH", "XRP", "ADA", "DOGE", "SOL", "TRX", "XLM", "DOT", "LTC", "DAI", "LINK", "ICP", "SAND"] # "STX", 
    URL_BASE: https://www.cryptodatadownload.com/cdd/
    STRATEGIES : ["Strategy2"]