version: 1
disable_existing_loggers: true

formatters:
    console:
      format: "[%(asctime)s][%(levelname)s][%(filename)s][%(module)s.%(funcName)s:%(lineno)d] %(message)s"
    file:
      format: "[%(asctime)s][%(levelname)s][%(filename)s][%(module)s.%(funcName)s:%(lineno)d] %(message)s"
    network:
      format: "[sampleProject][%(levelname)s] %(message)s"

handlers:
    console:
      class: utils.color_logger.ColorHandler
      level: INFO
      formatter: console

      stream: ext://sys.stdout
      colors:
        debug: magenta
        info: cyan
        warning: yellow
        error: red
        critical: red

    file_handler:
      class: utils.color_logger.MakeFileHandler
      level: INFO
      formatter: file

      filename: logs/output.log
      encoding: utf8

root:
    level: INFO
    handlers:
      - console
      - file_handler
    propogate: yes

None:
    level: INFO
    handlers:
      - console
      - file_handler
    propogate: yes

loggers:
    cryptos:
      level: INFO
