# MODEL META UB - LGBM - PDV
strategy_2:
    TARGET : POS_BINARY_FUTUR_TARGET_2
    WEIGHT : WEIGHT
    FEATURES:
        # - TARGET_NORMALIZED_0.5
        - TARGET_NORMALIZED_1
        - TARGET_NORMALIZED_2
        - TARGET_NORMALIZED_7
        - TARGET_NORMALIZED_15
        - TARGET_NORMALIZED_30
        - TARGET_NORMALIZED_45
        - TARGET_NORMALIZED_90
        # - CLOSE_TREND_0.5
        - CLOSE_TREND_7
        - CLOSE_TREND_15
        - CLOSE_TREND_30
        - CLOSE_TREND_45
        # - CLOSE_TREND_90
        # - VOLUME_NORMALIZED_1
        # - VOLUME_NORMALIZED_7
        # - VOLUME_NORMALIZED_30
        # - VOLUME_NORMALIZED_90
        # - DIFF_TO_MARKET_0.5 # market distance
        - DIFF_TO_MARKET_1
        - DIFF_TO_MARKET_7
        - DIFF_TO_MARKET_30
        # - DIFF_TO_MARKET_90
        # - CLOSE_ROLLING_STD_0.5D
        - CLOSE_ROLLING_STD_1D # target std past X days
        - CLOSE_ROLLING_STD_7D
        - CLOSE_ROLLING_STD_30D
        # - CLOSE_ROLLING_STD_45D
        # - DIFF_GOLD_NORMALIZED_7
        # - DIFF_GOLD_NORMALIZED_30
        # - DIFF_GOLD_NORMALIZED_90
        - DIFF_S&P_NORMALIZED_7
        - DIFF_S&P_NORMALIZED_30
        # - DIFF_S&P_NORMALIZED_90
        # - DIFF_BRENT_NORMALIZED_7
        # - DIFF_BRENT_NORMALIZED_30
        # - DIFF_BRENT_NORMALIZED_90
        # - DAY_OF_YEAR
        - WEEK_DAY
        # - HOUR
        # - MONTH
    categorical_features:
        # - DAY_OF_YEAR
        - WEEK_DAY
        # - HOUR
        # - MONTH
    seed: 5432
    n_splits: 1
    parameters:
        objective: binary
        metric: binary_logloss
        max_depth: 6
        min_child_samples : 30
        colsample_bytree: 0.75
        subsample: 0.8
        learning_rate: 0.007
        num_iteration: 900
        reg_alpha : 3
        reg_lambda: 0
        n_jobs: -1
        verbose : -1
        early_stopping_round: 100