# MODEL META UB - LGBM - PDV
strategy_2:
    TARGET : DELTA_TARGET_1
    WEIGHT : WEIGHT
    FEATURES:
        - DELTA_CLOSE_MEAN_1
        - DELTA_CLOSE_MEAN_5
        - DELTA_CLOSE_MEAN_9
        - DELTA_CLOSE_MEAN_13
        - DELTA_CLOSE_MEAN_17
        - DELTA_CLOSE_MEAN_21
        - DELTA_CLOSE_MEAN_25
        - DELTA_CLOSE_MEAN_57
        - DELTA_CLOSE_MEAN_121
        - DELTA_CLOSE_MEAN_189
        - DELTA_CLOSE_2
        - DELTA_CLOSE_3
        - DELTA_CLOSE_4
        - DELTA_CLOSE_5
        - DELTA_CLOSE_6
        - DELTA_CLOSE_7
        - DELTA_CLOSE_8
        - DELTA_CLOSE_9
        - DELTA_CLOSE_10
        - DELTA_CLOSE_11
        - DELTA_CLOSE_12
        - DELTA_CLOSE_13
        - DELTA_CLOSE_14
        - DELTA_CLOSE_15
        - DELTA_CLOSE_16
        - DELTA_CLOSE_17
        - DELTA_CLOSE_18
        - DELTA_CLOSE_19
        - DELTA_CLOSE_20
        - DELTA_CLOSE_21
        - DELTA_CLOSE_22
        - DELTA_CLOSE_23
        - DELTA_CLOSE_24
        - STD_CLOSE_5
        - STD_CLOSE_9
        - STD_CLOSE_13
        - STD_CLOSE_17
        - STD_CLOSE_25
        - STD_CLOSE_57
        - STD_CLOSE_121
        - STD_CLOSE_189
        - DELTA_VOLUME_MEAN_1
        - DELTA_VOLUME_MEAN_5
        - DELTA_VOLUME_MEAN_9
        - DELTA_VOLUME_MEAN_13
        - DELTA_VOLUME_MEAN_17
        - DELTA_VOLUME_MEAN_21
        - DELTA_VOLUME_MEAN_25
        - DELTA_VOLUME_MEAN_57
        - DELTA_VOLUME_MEAN_121
        - DELTA_VOLUME_MEAN_189
        - DAY_OF_YEAR
        - WEEK_DAY
        - HOUR
        # - MONTH
    categorical_features:
    seed: 5432
    n_splits: 1
    parameters:
        objective: regression
        metric: mape
        max_depth: 6
        min_child_samples : 50
        colsample_bytree: 0.75
        subsample: 0.75
        learning_rate: 0.01
        num_iteration: 1000
        reg_alpha : 0
        reg_lambda: 1
        n_jobs: -1
        verbose : -1
        early_stopping_round: 100