-- AUTO-GENERATED by src/data_store/schema_sql.py — do not edit by hand.
-- Regenerate: python -m scripts.generate_schema_sql
-- Every statement is idempotent (CREATE TABLE/INDEX IF NOT EXISTS).


-- [reference] sp500_tickers  (pk: ticker)

CREATE TABLE IF NOT EXISTS "sp500_tickers" (
    "ticker" TEXT NOT NULL,
    "name" TEXT,
    "sector" TEXT,
    "industry_group" TEXT,
    "sub_industry" TEXT,
    "cik" TEXT,
    PRIMARY KEY ("ticker")
);

-- [extract] prices  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "prices" (
    "date" TIMESTAMP NOT NULL,
    "open" DOUBLE PRECISION,
    "high" DOUBLE PRECISION,
    "low" DOUBLE PRECISION,
    "close" DOUBLE PRECISION,
    "volume" DOUBLE PRECISION,
    "ticker" TEXT NOT NULL,
    PRIMARY KEY ("ticker", "date")
);

-- [extract] dividends  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "dividends" (
    "date" TIMESTAMP NOT NULL,
    "ticker" TEXT NOT NULL,
    "dividend" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "date")
);

-- [extract] short_interest  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "short_interest" (
    "date" TIMESTAMP NOT NULL,
    "ticker" TEXT NOT NULL,
    "short_volume" DOUBLE PRECISION,
    "total_volume" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "date")
);

-- [extract] fundamentals_history  (pk: ticker, as_of)

CREATE TABLE IF NOT EXISTS "fundamentals_history" (
    "ticker" TEXT NOT NULL,
    "as_of" DATE NOT NULL,
    "fiscal_end" DATE,
    "totalRevenue" DOUBLE PRECISION,
    "netIncome" DOUBLE PRECISION,
    "grossMargins" DOUBLE PRECISION,
    "operatingMargins" DOUBLE PRECISION,
    "profitMargins" DOUBLE PRECISION,
    "returnOnEquity" DOUBLE PRECISION,
    "debtToEquity" DOUBLE PRECISION,
    "ebitda" DOUBLE PRECISION,
    "freeCashflow" DOUBLE PRECISION,
    "operatingCashFlow" DOUBLE PRECISION,
    "researchAndDevelopment" DOUBLE PRECISION,
    "stockholdersEquity" DOUBLE PRECISION,
    "sharesOutstanding" DOUBLE PRECISION,
    "cash" DOUBLE PRECISION,
    "longTermDebt" DOUBLE PRECISION,
    "shortTermDebt" DOUBLE PRECISION,
    "totalLiabilities" DOUBLE PRECISION,
    "currentAssets" DOUBLE PRECISION,
    "currentLiabilities" DOUBLE PRECISION,
    "goodwill" DOUBLE PRECISION,
    "totalAssets" DOUBLE PRECISION,
    "sellingGeneralAdmin" DOUBLE PRECISION,
    "stockBasedComp" DOUBLE PRECISION,
    "acquisitions" DOUBLE PRECISION,
    "interestExpense" DOUBLE PRECISION,
    "revenue_q" DOUBLE PRECISION,
    "netIncome_q" DOUBLE PRECISION,
    "ebitda_q" DOUBLE PRECISION,
    "freeCashflow_q" DOUBLE PRECISION,
    "revenueGrowth" DOUBLE PRECISION,
    "earningsGrowth" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "as_of")
);

-- [extract] fundamentals_latest  (pk: ticker)

CREATE TABLE IF NOT EXISTS "fundamentals_latest" (
    "ticker" TEXT NOT NULL,
    "as_of" DATE,
    "marketCap" DOUBLE PRECISION,
    "trailingPE" DOUBLE PRECISION,
    "forwardPE" DOUBLE PRECISION,
    "sector" TEXT,
    "industry" TEXT,
    "shortName" TEXT,
    PRIMARY KEY ("ticker")
);

-- [extract] earnings_surprises  (pk: ticker, earnings_date)

CREATE TABLE IF NOT EXISTS "earnings_surprises" (
    "ticker" TEXT NOT NULL,
    "earnings_date" TIMESTAMP NOT NULL,
    "eps_estimate" DOUBLE PRECISION,
    "eps_actual" DOUBLE PRECISION,
    "surprise_pct" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "earnings_date")
);

-- [extract] macro  (pk: date)

CREATE TABLE IF NOT EXISTS "macro" (
    "date" TIMESTAMP NOT NULL,
    "yield_3m" DOUBLE PRECISION,
    "yield_2y" DOUBLE PRECISION,
    "yield_10y" DOUBLE PRECISION,
    "yield_30y" DOUBLE PRECISION,
    "yield_curve_10y2y" DOUBLE PRECISION,
    "yield_curve_10y3m" DOUBLE PRECISION,
    "vix" DOUBLE PRECISION,
    "ig_credit_spread" DOUBLE PRECISION,
    "hy_credit_spread" DOUBLE PRECISION,
    "breakeven_10y" DOUBLE PRECISION,
    PRIMARY KEY ("date")
);

-- [extract] employees_history  (pk: ticker, as_of)

CREATE TABLE IF NOT EXISTS "employees_history" (
    "ticker" TEXT NOT NULL,
    "as_of" TIMESTAMP NOT NULL,
    "period" TIMESTAMP,
    "employees" BIGINT,
    "form_type" TEXT,
    "accession_number" TEXT,
    PRIMARY KEY ("ticker", "as_of")
);

-- [extract] management_history  (pk: ticker, as_of)

CREATE TABLE IF NOT EXISTS "management_history" (
    "ticker" TEXT NOT NULL,
    "as_of" TIMESTAMP NOT NULL,
    "period" TIMESTAMP,
    "form_type" TEXT,
    "accession_number" TEXT,
    "ceo_name" TEXT,
    "ceo_age" DOUBLE PRECISION,
    "founder_present" BIGINT,
    "founder_ceo" BIGINT,
    "n_officers" BIGINT,
    "avg_officer_age" DOUBLE PRECISION,
    "heldPercentInsiders" TEXT,
    "heldPercentInstitutions" TEXT,
    "family_owned" TEXT,
    PRIMARY KEY ("ticker", "as_of")
);

-- [extract] sec_filings_index  (pk: ticker, accession_number)

CREATE TABLE IF NOT EXISTS "sec_filings_index" (
    "ticker" TEXT NOT NULL,
    "cik" TEXT,
    "company_name" TEXT,
    "form" TEXT,
    "filing_date" TIMESTAMP,
    "accession_number" TEXT NOT NULL,
    "primary_document" TEXT,
    "doc_url" TEXT,
    PRIMARY KEY ("ticker", "accession_number")
);
CREATE INDEX IF NOT EXISTS ix_sec_filings_index_filing_date ON "sec_filings_index" ("filing_date");

-- [extract] google_trends  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "google_trends" (
    "date" TIMESTAMP NOT NULL,
    "ticker" TEXT NOT NULL,
    "search_interest" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "date")
);

-- [extract] wiki_pageviews  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "wiki_pageviews" (
    "date" TIMESTAMP NOT NULL,
    "ticker" TEXT NOT NULL,
    "pageviews" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "date")
);

-- [extract] ticker_embeddings  (pk: ticker)

CREATE TABLE IF NOT EXISTS "ticker_embeddings" (
    "ticker" TEXT NOT NULL,
    "embedding" DOUBLE PRECISION[],
    PRIMARY KEY ("ticker")
);

-- SKIPPED (source missing): cusip_ticker_map <- cusip_ticker_map.parquet

-- SKIPPED (source missing): institutional_holdings <- institutional_holdings.parquet

-- SKIPPED (source missing): def14a_llm <- def14a_llm.parquet

-- SKIPPED (source missing): ticker_descriptions <- ticker_descriptions.parquet

-- [aggregate] cube  (pk: ticker, date, target_horizon)

CREATE TABLE IF NOT EXISTS "cube" (
    "date" TIMESTAMP NOT NULL,
    "ticker" TEXT NOT NULL,
    "target_rank" DOUBLE PRECISION,
    "target_zscore" DOUBLE PRECISION,
    "target_horizon" BIGINT NOT NULL,
    "mom_12_1" DOUBLE PRECISION,
    "rev_5" DOUBLE PRECISION,
    "rev_21" DOUBLE PRECISION,
    "vol_21" DOUBLE PRECISION,
    "vol_63" DOUBLE PRECISION,
    "ma_ratio_50" DOUBLE PRECISION,
    "ma_ratio_200" DOUBLE PRECISION,
    "high_prox_252" DOUBLE PRECISION,
    "gap_21" DOUBLE PRECISION,
    "range_21" DOUBLE PRECISION,
    "peer_mom_63" DOUBLE PRECISION,
    "max_21" DOUBLE PRECISION,
    "ret_skew_126" DOUBLE PRECISION,
    "downside_vol_63" DOUBLE PRECISION,
    "idio_vol_63" DOUBLE PRECISION,
    "macd" DOUBLE PRECISION,
    "macd_hist" DOUBLE PRECISION,
    "rsi_14" DOUBLE PRECISION,
    "atr_14" DOUBLE PRECISION,
    "f_earnings_yield_vs_peers" DOUBLE PRECISION,
    "f_earnings_yield_xs" DOUBLE PRECISION,
    "f_sales_yield_vs_peers" DOUBLE PRECISION,
    "f_sales_yield_xs" DOUBLE PRECISION,
    "f_book_yield_vs_peers" DOUBLE PRECISION,
    "f_book_yield_xs" DOUBLE PRECISION,
    "f_fcf_yield_vs_peers" DOUBLE PRECISION,
    "f_fcf_yield_xs" DOUBLE PRECISION,
    "f_ebitda_to_ev_vs_peers" DOUBLE PRECISION,
    "f_ebitda_to_ev_xs" DOUBLE PRECISION,
    "f_grossMargins_vs_peers" DOUBLE PRECISION,
    "f_grossMargins_xs" DOUBLE PRECISION,
    "f_operatingMargins_vs_peers" DOUBLE PRECISION,
    "f_operatingMargins_xs" DOUBLE PRECISION,
    "f_profitMargins_vs_peers" DOUBLE PRECISION,
    "f_profitMargins_xs" DOUBLE PRECISION,
    "f_returnOnEquity_vs_peers" DOUBLE PRECISION,
    "f_returnOnEquity_xs" DOUBLE PRECISION,
    "f_debtToEquity_vs_peers" DOUBLE PRECISION,
    "f_debtToEquity_xs" DOUBLE PRECISION,
    "f_revenueGrowth_vs_peers" DOUBLE PRECISION,
    "f_revenueGrowth_xs" DOUBLE PRECISION,
    "f_earningsGrowth_vs_peers" DOUBLE PRECISION,
    "f_earningsGrowth_xs" DOUBLE PRECISION,
    "f_fcf_margin_vs_peers" DOUBLE PRECISION,
    "f_fcf_margin_xs" DOUBLE PRECISION,
    "f_accruals_vs_peers" DOUBLE PRECISION,
    "f_accruals_xs" DOUBLE PRECISION,
    "f_fcf_growth_vs_peers" DOUBLE PRECISION,
    "f_fcf_growth_xs" DOUBLE PRECISION,
    "f_shares_growth_vs_peers" DOUBLE PRECISION,
    "f_shares_growth_xs" DOUBLE PRECISION,
    "f_gross_margin_chg_vs_peers" DOUBLE PRECISION,
    "f_gross_margin_chg_xs" DOUBLE PRECISION,
    "f_rd_intensity_vs_peers" DOUBLE PRECISION,
    "f_rd_intensity_xs" DOUBLE PRECISION,
    "f_gross_profitability_vs_peers" DOUBLE PRECISION,
    "f_gross_profitability_xs" DOUBLE PRECISION,
    "f_q_rev_growth_vs_peers" DOUBLE PRECISION,
    "f_q_rev_growth_xs" DOUBLE PRECISION,
    "f_rev_growth_accel_vs_peers" DOUBLE PRECISION,
    "f_rev_growth_accel_xs" DOUBLE PRECISION,
    "f_q_earnings_growth_vs_peers" DOUBLE PRECISION,
    "f_q_earnings_growth_xs" DOUBLE PRECISION,
    "f_q_margin_vs_ttm_vs_peers" DOUBLE PRECISION,
    "f_q_margin_vs_ttm_xs" DOUBLE PRECISION,
    "f_y_rev_growth_vs_peers" DOUBLE PRECISION,
    "f_y_rev_growth_xs" DOUBLE PRECISION,
    "f_y_rev_growth_accel_vs_peers" DOUBLE PRECISION,
    "f_y_rev_growth_accel_xs" DOUBLE PRECISION,
    "f_y_earnings_growth_vs_peers" DOUBLE PRECISION,
    "f_y_earnings_growth_xs" DOUBLE PRECISION,
    "f_y_margin_vs_ttm_vs_peers" DOUBLE PRECISION,
    "f_y_margin_vs_ttm_xs" DOUBLE PRECISION,
    "f_net_debt_to_ebitda_vs_peers" DOUBLE PRECISION,
    "f_net_debt_to_ebitda_xs" DOUBLE PRECISION,
    "f_interest_coverage_vs_peers" DOUBLE PRECISION,
    "f_interest_coverage_xs" DOUBLE PRECISION,
    "f_current_ratio_vs_peers" DOUBLE PRECISION,
    "f_current_ratio_xs" DOUBLE PRECISION,
    "f_cash_to_debt_vs_peers" DOUBLE PRECISION,
    "f_cash_to_debt_xs" DOUBLE PRECISION,
    "f_sga_intensity_vs_peers" DOUBLE PRECISION,
    "f_sga_intensity_xs" DOUBLE PRECISION,
    "f_sga_growth_vs_peers" DOUBLE PRECISION,
    "f_sga_growth_xs" DOUBLE PRECISION,
    "f_operating_leverage_vs_peers" DOUBLE PRECISION,
    "f_operating_leverage_xs" DOUBLE PRECISION,
    "f_acquisition_intensity_vs_peers" DOUBLE PRECISION,
    "f_acquisition_intensity_xs" DOUBLE PRECISION,
    "f_goodwill_growth_vs_peers" DOUBLE PRECISION,
    "f_goodwill_growth_xs" DOUBLE PRECISION,
    "f_sbc_intensity_vs_peers" DOUBLE PRECISION,
    "f_sbc_intensity_xs" DOUBLE PRECISION,
    "f_sbc_to_ocf_vs_peers" DOUBLE PRECISION,
    "f_sbc_to_ocf_xs" DOUBLE PRECISION,
    "f_intrinsic_yield_vs_peers" DOUBLE PRECISION,
    "f_intrinsic_yield_xs" DOUBLE PRECISION,
    "f_earnings_yield_vs_hist" DOUBLE PRECISION,
    "f_sales_yield_vs_hist" DOUBLE PRECISION,
    "f_book_yield_vs_hist" DOUBLE PRECISION,
    "f_fcf_yield_vs_hist" DOUBLE PRECISION,
    "f_ebitda_to_ev_vs_hist" DOUBLE PRECISION,
    "f_intrinsic_yield_vs_hist" DOUBLE PRECISION,
    "f_profitable" DOUBLE PRECISION,
    "f_fcf_positive" DOUBLE PRECISION,
    "f_negative_equity" DOUBLE PRECISION,
    "f_hyper_growth" DOUBLE PRECISION,
    "f_fwd_eps_yield_vs_peers" DOUBLE PRECISION,
    "f_fwd_eps_yield_xs" DOUBLE PRECISION,
    "f_eps_expectation_growth_vs_peers" DOUBLE PRECISION,
    "f_eps_expectation_growth_xs" DOUBLE PRECISION,
    "f_eps_surprise_last_vs_peers" DOUBLE PRECISION,
    "f_eps_surprise_last_xs" DOUBLE PRECISION,
    "f_eps_surprise_4q_avg_vs_peers" DOUBLE PRECISION,
    "f_eps_surprise_4q_avg_xs" DOUBLE PRECISION,
    "f_founder_led_vs_peers" DOUBLE PRECISION,
    "f_founder_led_xs" DOUBLE PRECISION,
    "f_founder_ceo_vs_peers" DOUBLE PRECISION,
    "f_founder_ceo_xs" DOUBLE PRECISION,
    "f_ceo_age_vs_peers" DOUBLE PRECISION,
    "f_ceo_age_xs" DOUBLE PRECISION,
    "f_n_officers_vs_peers" DOUBLE PRECISION,
    "f_n_officers_xs" DOUBLE PRECISION,
    "f_avg_officer_age_vs_peers" DOUBLE PRECISION,
    "f_avg_officer_age_xs" DOUBLE PRECISION,
    "f_employee_growth_vs_peers" DOUBLE PRECISION,
    "f_employee_growth_xs" DOUBLE PRECISION,
    "f_revenue_per_employee_vs_peers" DOUBLE PRECISION,
    "f_revenue_per_employee_xs" DOUBLE PRECISION,
    "comp_value" DOUBLE PRECISION,
    "comp_quality" DOUBLE PRECISION,
    "comp_growth" DOUBLE PRECISION,
    "comp_distress" DOUBLE PRECISION,
    "comp_capital_allocation" DOUBLE PRECISION,
    "comp_expectations" DOUBLE PRECISION,
    "comp_management" DOUBLE PRECISION,
    "comp_workforce" DOUBLE PRECISION,
    "comp_technical" DOUBLE PRECISION,
    "beta_market" DOUBLE PRECISION,
    "beta_momentum" DOUBLE PRECISION,
    "beta_resvol" DOUBLE PRECISION,
    "beta_size" DOUBLE PRECISION,
    "beta_value" DOUBLE PRECISION,
    "beta_quality" DOUBLE PRECISION,
    "beta_oil" DOUBLE PRECISION,
    "beta_gold" DOUBLE PRECISION,
    "beta_USD/EUR" DOUBLE PRECISION,
    "beta_d_yield_10y" DOUBLE PRECISION,
    "beta_d_yield_curve" DOUBLE PRECISION,
    "beta_d_vix" DOUBLE PRECISION,
    "beta_d_breakeven_10y" DOUBLE PRECISION,
    "beta_sector" DOUBLE PRECISION,
    "beta_market_simple" DOUBLE PRECISION,
    "peers" TEXT,
    PRIMARY KEY ("ticker", "date", "target_horizon")
);

-- [aggregate] cube_signal  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "cube_signal" (
    "date" TIMESTAMP NOT NULL,
    "ticker" TEXT NOT NULL,
    "signal" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "date")
);

-- [aggregate] predictions  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "predictions" (
    "date" TIMESTAMP NOT NULL,
    "ticker" TEXT NOT NULL,
    "z_30" DOUBLE PRECISION,
    "pred_elasticnet_h30" DOUBLE PRECISION,
    "pred_lightgbm_h30" DOUBLE PRECISION,
    "z_60" DOUBLE PRECISION,
    "pred_elasticnet_h60" DOUBLE PRECISION,
    "pred_lightgbm_h60" DOUBLE PRECISION,
    "z_90" DOUBLE PRECISION,
    "pred_elasticnet_h90" DOUBLE PRECISION,
    "pred_lightgbm_h90" DOUBLE PRECISION,
    "combined" DOUBLE PRECISION,
    "signal" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "date")
);
