resources:
  base_path : C:\Users\de larrard alexandre\Documents\repos_github\PEA\
  data: data/crypto

urls:
  reuters: https://www.reuters.com


stock_modelling_to_sector:
  TARGET: "TARGET_STOCK_+5D_SECTOR_MARKET"
  WEIGHT: WEIGHT
  FEATURES:
    # - WEEK_DAY 
    # - MONTH_DAY 
    - WEEK
    - COUNTRY
    - SECTOR
    - STOCK_DISTANCE_TO_MARKET_SECTOR_1W_MEAN
    - STOCK_DISTANCE_TO_MARKET_SECTOR_2W_MEAN
    - STOCK_DISTANCE_TO_MARKET_SECTOR_4W_MEAN
    - STOCK_DISTANCE_TO_MARKET_SECTOR_8W_MEAN
    - STOCK_DELTA_1Y_TREND_SECTOR_MARKET
    - VIX_0D_TO_2W_MEAN
    - SECTOR_STOCK_1W_STD_RATIO
    - SECTOR_STOCK_2W_STD_RATIO
    - DISTANCE_VOLUME_0D_TO_2W_MEAN
    - DISTANCE_VOLUME_0D_TO_4W_MEAN
    - DISTANCE_VOLUME_0D_TO_8W_MEAN
  categorical_features:
    # - WEEK_DAY 
    - WEEK
    - SECTOR
    - COUNTRY
  seed: 5432
  n_splits: 5
  parameters:
    objective: "regression"
    eval_metric: "mape"
    metric: 'mape'
    max_depth: 7
    min_data_in_leaf: 65
    colsample_bytree: 0.75
    subsample: 0.75
    learning_rate: 0.1
    num_iteration: 5000
    lambda_l1 : 2
    n_jobs: 7
    verbose_eval: 1000
    verbose : -1
    early_stopping_round: 40

  
sector_modelling_to_market:
  TARGET: "TARGET_SECTOR_+5D_TO_MARKET"
  WEIGHT: WEIGHT
  FEATURES:
    - WEEK_DAY 
    - MONTH_DAY 
    - WEEK
    - COUNTRY
    - SECTOR
    - VALUE_INFLATION
    - VALUE_LT_RATES
  categorical_features:
    - WEEK_DAY 
    - WEEK
    - SECTOR
    - COUNTRY
  seed: 5432
  n_splits: 5
  parameters:
    objective: "regression"
    eval_metric: "mape"
    metric: 'mape'
    max_depth: 7
    min_data_in_leaf: 65
    colsample_bytree: 0.75
    subsample: 0.75
    learning_rate: 0.1
    num_iteration: 5000
    lambda_l1 : 2
    n_jobs: 7
    verbose_eval: 1000
    verbose : -1
    early_stopping_round: 40


regression_model:
  TARGET: "_P/E_+1Q_Y"
  FEATURES:
    # - '%_NET_PROFIT_MARGIN'
    # - '%_R&D_IN_OPERATING_INCOME'
    # - '%_SALES_GENERAL_IN_REVENUE'
    # - '%_TAXES_&_EXTRA_IN_TOTAL_REVENUE'
    - '%_YOY_NET_INCOME_BEFORE_EXTRA_ITEMS'
    - '%_YOY_OPERATING_INCOME'
    # - '%_YOY_TOTAL_REVENUE'
    # - 'BALANCE_%_CASH / TOTAL_DEBT'
    - 'BALANCE_%_CURRENT_ASSET / CURRENT_DEBT'
    # - 'BALANCE_%_SHARE_GOODWILL_ASSETS'
    - 'BALANCE_TREND_SHAREHOLDERS_EQUITY'
    - 'BALANCE_%_MARKET_CAP / SHAREHOLDERS_EQUITY'
    - 'CASH_%_DIVIDENDS IN ACTIVITY_CASH'
    - 'CASH_%_INTO_ACQUISITION'
    - 'CASH_%_INTO_ACTIVITY'
    - 'CASH_%_FINANCE IN ACTIVITY_CASH'
    - 'CASH_TREND_FREE_CASH_FLOW'
    - 'LONG_TREND_NET_INCOME_BEFORE_EXTRA_ITEMS'
    - 'LONG_TREND_OP_INCOME'
    - 'LONG_TREND_R&D_SHARE_OPERATING_INCOME'
    - 'LONG_TREND_TOTAL_REVENUE'
    - 'DISTANCE MARKET_CAP / INTRINSIC '
    - 'STOCK_%_52_WEEKS'
    - '_TOTAL_REVENUE'
    - '_NET_INCOME_BEFORE_EXTRA_ITEMS'
    - "SECTOR"
    - '_P/E_Y'
    - "_P/E_Y-1"
    - 'INTRINSIC_VALUE'
    - 'STOCK_% TREND_NET_INCOME_WO_EXTRA - STOCK_TREND'
    # - 'TREND_OP_INCOME / TREND_TOTAL_REVENUE'
    # - 'COUNTRY'
    # - 'SPECIFIC'
    # - 'MEAN_%_YOY_NET_INCOME_BEFORE_EXTRA_ITEMS'
    # - '%_DISTANCE_%_NET_PROFIT_MARGIN'
    # - '%_DISTANCE_%_YOY_TOTAL_REVENUE'
    - '%_DISTANCE_BALANCE_%_SHARE_GOODWILL_ASSETS'
    - '%_DISTANCE__P/E_Y'
    # - '%_DISTANCE_STOCK_%_52_WEEKS'
    # - '%_YOY_NET_INCOME_BEFORE_EXTRA_ITEMS-1'
    # - 'TEAM_#_INDEPENDENT_DIRECTOR'
    # - 'TEAM_CEO_APPOINTED'
    # - 'TEAM_LEADER_AGE_AVG'
    # - 'SUB INDUSTRY'
    # - '%_DISTANCE_BALANCE_TREND_CURRENT_ASSET / CURRENT_DEBT'
  categorical_features:
    - "SECTOR"
    # - 'SUB INDUSTRY'
    # - 'COUNTRY'
    # - 'SPECIFIC'
  seed: 5432
  n_splits: 5
  parameters:
    objective: "regression"
    eval_metric: "mape"
    metric: 'mape'
    max_depth: 7
    min_data_in_leaf: 5
    colsample_bytree: 0.75
    subsample: 0.75
    learning_rate: 0.003
    num_iteration: 4000
    lambda_l1 : 1
    n_jobs: 7
    # verbose_eval: 100
    verbose : -1
    early_stopping_round: 40