SELECT cpdv.DATE, cpdv.CODE_PRGE AS UB_CODE, cpdv.CODE_PRD AS PRODUIT_STD_CODE,
cpdv.CODE_PDV AS COD_SITE, cpdv.PPTTC AS PRIX_UNITAIRE, cpdv.CODE_BASE,
cpdv.POIDS AS POIDS_COMMANDE, cpdv.UNITE_FACTUR
FROM commandes_pdv cpdv
