SELECT vg.DATE_VENTE AS DATE, vg.CODE_PDV AS COD_SITE, vg.CODE_PRGE AS UB_CODE, vg.MNT_VENTE AS MNT_VTE, vg.QTE_VENTE AS QTE_VTE,
       vg.POIDS_VENTE_ESTIM, rpg.LIB_PRGE AS UB_NOM, rpg.CODE_NOMENCLATURE,
       rpdv.CODE_VOCATION, rpdv.CODE_BASE,
       rpdv.SURFACE_TOTALE, rpdv.NB_CAISSES, rpdv.DATE_ACTIVATION_TECH, rpdv.DATE_DESACTIVATION_TECH
FROM ventes_generiques vg LEFT JOIN ref_produit_generique rpg ON vg.CODE_PRGE = rpg.CODE_PRGE
LEFT JOIN ref_point_de_vente rpdv ON vg.CODE_PDV = rpdv.CODE_PDV
WHERE vg.CODE_PDV IN (1221, 1574, 1599, 4951, 6555)
--        ub_mapping.LIB_FAMILLE AS SOUS_FAMILLE
-- LEFT JOIN (SELECT DISTINCT CODE_PRGE, LIB_FAMILLE FROM ref_produit_standard) AS ub_mapping ON ub_mapping.CODE_PRGE = rpg.CODE_PRGE
-- AND ub_mapping.LIB_FAMILLE IN ('TOMATE', 'BANANE', 'FRAISE', 'SALADE');
-- New PDV used for july test (2811, 1160, 4647, 1926, 5548);
-- Old PDV (1221, 1574, 1599, 4951, 6555);
