"""
schema_sql.py  (src/data_store/schema_sql.py)
---------------------------------------------
Generate the authoritative `CREATE TABLE IF NOT EXISTS` DDL for every table in
the registry by introspecting the real dtypes of the flat files in data/.

Kept generated (not hand-written) so wide/volatile tables like `cube` (159 cols)
stay correct without hand-maintaining 159 column definitions. The output is
written to sql/schema.sql, which the Postgres container runs on first init.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd
from pandas.api import types as ptypes

from src.data_store.io import read_source
from src.data_store.schema_registry import ALL_TABLES, TableSpec

# Columns that are zero-padded string identifiers, never numeric — forcing them
# to TEXT preserves leading zeros (SEC CIK "0000320193" would lose them as BIGINT).
_TEXT_IDENTIFIER_COLS = {"cik"}


def _sql_type(col: str, dtype, spec: TableSpec | None = None) -> str:
    if spec is not None and col in spec.date_type_cols:
        return "DATE"
    if col.lower() in _TEXT_IDENTIFIER_COLS:
        return "TEXT"
    if ptypes.is_datetime64_any_dtype(dtype):
        return "TIMESTAMP"
    if ptypes.is_bool_dtype(dtype):
        return "BOOLEAN"
    if ptypes.is_integer_dtype(dtype):
        return "BIGINT"
    if ptypes.is_float_dtype(dtype):
        return "DOUBLE PRECISION"
    return "TEXT"


def _quote(ident: str) -> str:
    """Quote an identifier so mixed-case / slash column names survive (e.g.
    beta_USD/EUR). Postgres folds unquoted names to lowercase, which would break
    round-tripping such columns."""
    return '"' + ident.replace('"', '""') + '"'


def _columns_for(spec: TableSpec, df: pd.DataFrame) -> list[tuple[str, str]]:
    """Return ordered (column_name, sql_type). Collapses a vector family
    (e0..eN) into a single array column when the spec requests it."""
    if spec.vector_col and spec.vector_prefix:
        prefix = spec.vector_prefix
        vec_cols = [c for c in df.columns if c.startswith(prefix)
                    and c[len(prefix):].isdigit()]
        # exclude the collapsed vector column itself: producers may already supply it as a
        # single pre-collapsed list column named `vector_col` (e.g. earning_calls_embedding,
        # ticker_embeddings) rather than e0..eN scalars -- without this it would be emitted
        # both as a scalar (in `other`) AND as the array below -> duplicate-column DDL.
        other = [c for c in df.columns if c not in vec_cols and c != spec.vector_col]
        cols = [(c, _sql_type(c, df[c].dtype, spec)) for c in other]
        cols.append((spec.vector_col, "DOUBLE PRECISION[]"))
        return cols
    return [(c, _sql_type(c, df[c].dtype, spec)) for c in df.columns]


def _reflect_columns(engine, name: str) -> list[tuple[str, str]]:
    """Ordered (column, SQL type) from the LIVE table's real schema (not sampled dtypes),
    so columns that are all-NaN in an early sample (e.g. gold before 2000) keep their true
    DOUBLE PRECISION type rather than being mis-inferred as TEXT."""
    from sqlalchemy import MetaData, Table
    tbl = Table(name, MetaData(), autoload_with=engine)
    return [(c.name, str(c.type)) for c in tbl.c]


def _ddl_from_columns(spec: TableSpec, cols: list[tuple[str, str]]) -> str:
    pk = set(spec.pk)
    lines = []
    for name, sqltype in cols:
        null = " NOT NULL" if name in pk else ""
        lines.append(f"    {_quote(name)} {sqltype}{null}")
    pk_clause = ", ".join(_quote(c) for c in spec.pk)
    lines.append(f"    PRIMARY KEY ({pk_clause})")
    body = ",\n".join(lines)
    ddl = [f"CREATE TABLE IF NOT EXISTS {_quote(spec.name)} (\n{body}\n);"]
    if spec.ticker_col and spec.ticker_col not in spec.pk:
        ddl.append(f"CREATE INDEX IF NOT EXISTS ix_{spec.name}_{spec.ticker_col} "
                   f"ON {_quote(spec.name)} ({_quote(spec.ticker_col)});")
    if spec.date_col and spec.date_col not in spec.pk:
        ddl.append(f"CREATE INDEX IF NOT EXISTS ix_{spec.name}_{spec.date_col} "
                   f"ON {_quote(spec.name)} ({_quote(spec.date_col)});")
    return "\n".join(ddl)


def _table_ddl(spec: TableSpec, df: pd.DataFrame) -> str:
    """DDL from a sample DataFrame's dtypes (flat-file source)."""
    return _ddl_from_columns(spec, _columns_for(spec, df))


def generate_schema_sql(data_dir: Path, engine=None) -> str:
    """Introspect every source file and return the full schema.sql text. For DB-only
    tables that have no flat source under data/ (created at runtime via ensure_table,
    e.g. macro_asset_prices, def14a_llm), fall back to introspecting the LIVE DB when an
    `engine` is given — so their real DDL is emitted instead of a SKIPPED comment."""
    from src.data_store.store import table_exists
    header = (
        "-- AUTO-GENERATED by src/data_store/schema_sql.py — do not edit by hand.\n"
        "-- Regenerate: python -m scripts.generate_schema_sql\n"
        "-- Every statement is idempotent (CREATE TABLE/INDEX IF NOT EXISTS).\n"
    )
    blocks = [header]
    for spec in ALL_TABLES:
        path = data_dir / spec.source
        if path.exists():                                     # flat-file: infer from dtypes
            ddl = _table_ddl(spec, read_source(spec, data_dir, nrows=200))
            src = "flat file"
        elif engine is not None and table_exists(engine, spec.name):
            ddl = _ddl_from_columns(spec, _reflect_columns(engine, spec.name))  # live DB: real types
            src = "live DB"
        else:
            blocks.append(f"-- SKIPPED (source missing): {spec.name} <- {spec.source}")
            continue
        blocks.append(f"-- [{spec.kind}] {spec.name}  (pk: {', '.join(spec.pk)}; from {src})")
        blocks.append(ddl)
    return "\n\n".join(blocks) + "\n"


def write_schema_sql(data_dir: Path, out_path: Path, engine=None) -> Path:
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(generate_schema_sql(data_dir, engine=engine), encoding="utf-8")
    return out_path
