#Use the python container image
FROM python:3.7.10

#Set the working directory to app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN apt-get update &&\
    apt-get install -y apt-utils &&\
    apt-get install -y gcc

# install packages
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# download resources en_core_web_lg
RUN python -m spacy download en_core_web_lg

CMD streamlit run app.py 

