-- AUTO-GENERATED by src/data_store/ddl.py — do not edit by hand.
-- Regenerate: python -m scripts.generate_schema_sql
-- Source of truth: src/data_store/schema.py (Tables).
-- Every statement is idempotent (CREATE TABLE/INDEX IF NOT EXISTS).
-- The cube_part_* tables are deliberately absent: they are private plumbing
-- between the cube sub-steps and are created by their owning step.

-- [reference] sp500_tickers  (pk: ticker)

CREATE TABLE IF NOT EXISTS "sp500_tickers" (
    "ticker" TEXT NOT NULL,
    "name" TEXT,
    "sector" TEXT,
    "industry_group" TEXT,
    "sub_industry" TEXT,
    "cik" TEXT,
    PRIMARY KEY ("ticker")
);

-- [extract] prices  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "prices" (
    "date" TIMESTAMP NOT NULL,
    "open" DOUBLE PRECISION,
    "high" DOUBLE PRECISION,
    "low" DOUBLE PRECISION,
    "close" DOUBLE PRECISION,
    "volume" DOUBLE PRECISION,
    "ticker" TEXT NOT NULL,
    PRIMARY KEY ("ticker", "date")
);

-- [extract] prices_dividends  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "prices_dividends" (
    "date" TIMESTAMP NOT NULL,
    "ticker" TEXT NOT NULL,
    "dividends" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "date")
);

-- [extract] sec_short_interest  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "sec_short_interest" (
    "date" TIMESTAMP NOT NULL,
    "ticker" TEXT NOT NULL,
    "short_volume" DOUBLE PRECISION,
    "total_volume" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "date")
);

-- [extract] sec_fails_to_deliver  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "sec_fails_to_deliver" (
    "ticker" TEXT NOT NULL,
    "date" DATE NOT NULL,
    "fails_quantity" DOUBLE PRECISION,
    "fails_value" DOUBLE PRECISION,
    "period" TEXT,
    PRIMARY KEY ("ticker", "date")
);

-- [extract] prices_macro  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "prices_macro" (
    "date" DATE NOT NULL,
    "ticker" TEXT NOT NULL,
    "close" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "date")
);

-- [extract] cusip_ticker_map  (pk: cusip)

CREATE TABLE IF NOT EXISTS "cusip_ticker_map" (
    "cusip" TEXT NOT NULL,
    "ticker" TEXT,
    PRIMARY KEY ("cusip")
);
CREATE INDEX IF NOT EXISTS ix_cusip_ticker_map_ticker ON "cusip_ticker_map" ("ticker");

-- [extract] fundamentals_history  (pk: ticker, as_of)
-- The PUBLICATION-EVENT grain: `as_of` is a FILING DATE, not a period end, and a row exists
-- for every date on which this ticker made >=1 extracted value newly public. Each row is a
-- COMPLETE SNAPSHOT (every column carries its latest-known value at that date), so a plain
-- `asof` merge needs no reconstruction -- and rows are append-only, so an earlier row keeps
-- its as-filed numbers forever. See data_extract/utils/fundamentals/build_history.py.
--
-- EXACTLY 69 columns, enumerated: 4 keys + 52 catalogue fields + 8 derived + `regime` +
-- 4 provenance, and the 60 value columns are in STATEMENT order rather than in the
-- tier-then-name order they are resolved in -- reading the table reads like the
-- statements it came from. `fiscal_quarter` labels which quarter of the ISSUER's own
-- year `fiscal_end` closes, on every row including the TTM and instant ones: a filer's
-- Q4 is not its Q1, and the calendar month of `fiscal_end` does not say which is which
-- for a 52/53-week or non-December filer. A `duration` field's column holds the TRAILING TWELVE MONTHS and an
-- `instant` field's the latest instant, on bare names -- `totalRevenue` always was the TTM,
-- which is why build_cube.yml and SECTOR_KPI_SCOPE need no renaming.
--
-- Gone from the legacy shape, each deliberately: `sector` / `industry_group` (a
-- slowly-changing dimension, joined from sp500_tickers rather than duplicated into a
-- point-in-time table); `revenueGrowth` / `earningsGrowth` (computed by pit.py at cube time
-- on a fixed 365-day as_of offset -- a row offset is ~9 months once an amendment row exists);
-- `employees` (text-sourced, so it lives in fundamentals_employees and a failed parse cannot
-- fail this build); `ebitda_q` / `freeCashflow_q` / `capexGlobal` and the ~170 columns whose
-- inputs left with the rebuild.

CREATE TABLE IF NOT EXISTS "fundamentals_history" (
    "ticker" TEXT NOT NULL,
    "as_of" DATE NOT NULL,
    "fiscal_end" DATE,
    "fiscal_quarter" BIGINT,
    -- the 60 value columns, in STATEMENT order (HISTORY_STATEMENT_ORDER)
    -- income statement -- revenue, general top line then the regime-specific ones
    "totalRevenue" DOUBLE PRECISION,
    "premiumsEarned" DOUBLE PRECISION,
    "netInterestIncome" DOUBLE PRECISION,
    "noninterestIncome" DOUBLE PRECISION,
    "netInvestmentIncome" DOUBLE PRECISION,
    "realizedInvestmentGains" DOUBLE PRECISION,
    "rentalIncome" DOUBLE PRECISION,
    -- cost of sales and gross result
    "costOfRevenue" DOUBLE PRECISION,
    "grossProfit" DOUBLE PRECISION,
    "grossMargins" DOUBLE PRECISION,
    -- operating expense
    "sellingGeneralAdmin" DOUBLE PRECISION,
    "researchAndDevelopment" DOUBLE PRECISION,
    "depAmort" DOUBLE PRECISION,
    "stockBasedComp" DOUBLE PRECISION,
    -- operating result
    "operatingIncome" DOUBLE PRECISION,
    "operatingMargins" DOUBLE PRECISION,
    "ebitda" DOUBLE PRECISION,
    -- below the operating line, down to the bottom line
    "interestExpense" DOUBLE PRECISION,
    "pretaxIncome" DOUBLE PRECISION,
    "incomeTaxExpense" DOUBLE PRECISION,
    "effectiveTaxRate" DOUBLE PRECISION,
    "netIncome" DOUBLE PRECISION,
    "profitMargins" DOUBLE PRECISION,
    "epsDiluted" DOUBLE PRECISION,
    -- single-quarter slices, beside the TTM lines they are cut from
    "revenue_q" DOUBLE PRECISION,
    "netIncome_q" DOUBLE PRECISION,
    -- cash flow
    "operatingCashFlow" DOUBLE PRECISION,
    "capex" DOUBLE PRECISION,
    "freeCashflow" DOUBLE PRECISION,
    -- balance sheet -- assets, current then long-lived
    "cash" DOUBLE PRECISION,
    "restrictedCash" DOUBLE PRECISION,
    "shortTermInvestments" DOUBLE PRECISION,
    "accountsReceivable" DOUBLE PRECISION,
    "inventory" DOUBLE PRECISION,
    "currentAssets" DOUBLE PRECISION,
    "ppeGross" DOUBLE PRECISION,
    "accumulatedDepreciation" DOUBLE PRECISION,
    "ppeNet" DOUBLE PRECISION,
    "goodwill" DOUBLE PRECISION,
    "intangiblesExGoodwill" DOUBLE PRECISION,
    "totalAssets" DOUBLE PRECISION,
    -- liabilities and debt, current then long-term, components then roll-ups
    "accountsPayable" DOUBLE PRECISION,
    "currentLiabilities" DOUBLE PRECISION,
    "shortTermDebt" DOUBLE PRECISION,
    "shortTermBorrowingsOnly" DOUBLE PRECISION,
    "longTermDebt" DOUBLE PRECISION,
    "longTermDebtCurrentOnly" DOUBLE PRECISION,
    "operatingLeaseLiability" DOUBLE PRECISION,
    "financeLeaseLiability" DOUBLE PRECISION,
    "totalDebt" DOUBLE PRECISION,
    "totalLiabilities" DOUBLE PRECISION,
    -- equity, and the two ratios that read off it
    "retainedEarnings" DOUBLE PRECISION,
    "minorityInterest" DOUBLE PRECISION,
    "stockholdersEquity" DOUBLE PRECISION,
    "returnOnEquity" DOUBLE PRECISION,
    "debtToEquity" DOUBLE PRECISION,
    -- share counts -- denominators, not statements
    "basicShares" DOUBLE PRECISION,
    "dilutedShares" DOUBLE PRECISION,
    "sharesOutstanding" DOUBLE PRECISION,
    "optionOverhang" DOUBLE PRECISION,
    "regime" TEXT,
    "publication_form" TEXT,
    "is_amendment" BOOLEAN,
    "amended_fiscal_end" DATE,
    "amended_fields" TEXT,
    PRIMARY KEY ("ticker", "as_of")
);
CREATE INDEX IF NOT EXISTS ix_fundamentals_history_ticker ON "fundamentals_history" ("ticker");

-- [extract] fundamentals_reason_codes  (pk: ticker, as_of, field, dc_code)
-- WHY a `fundamentals_history` cell is null, or why the value it does carry is not on the
-- field's nominal basis. Long rather than 39 `_DC` companion columns (which would be a ~50%
-- wider table, almost entirely NULL); the deviation from the Compustat-style shape the spec
-- asked for is reversible.
--
-- DENSE: one row per null-or-qualified cell at EVERY publication event, so the
-- zero-unexplained-nulls gate is a one-line LEFT JOIN on (ticker, as_of, field) and
-- "was this null explained on 2019-05-02?" stays a lookup rather than a window function.
-- Mostly repetition -- APA's totalLiabilities earns a row at all ~62 of its filing dates --
-- and that is the price of the snapshot contract, which a sparse state-change grain would
-- contradict. ~150-200k rows universe-wide.
--
-- The code vocabulary is closed and declared once, in
-- data_extract/utils/fundamentals/reason_codes.py; the build asserts every code against it.
--
-- TWO PAYLOAD COLUMNS, each NULL for every code but the one that owns it. `combined_into`
-- names the destination field for the `combined_into` code. `rejected_value` carries the
-- number a `failed_hard_guard` refused (plan-5b decision 46) -- it exists because a nulled
-- DERIVED value (a TTM, a `derived_identity` total) has no fact row anywhere, so without it
-- the refused number is simply lost and "did that guard null something CORRECT?" becomes
-- archaeology instead of a query. That question is the whole lesson of the 745 correct rows
-- an over-strict guard once nulled. Neither is part of the key: a field is folded into at
-- most one destination and refused at most one number per (field, code), so keying on either
-- would let two rows disagree rather than making the second impossible to write.

CREATE TABLE IF NOT EXISTS "fundamentals_reason_codes" (
    "ticker" TEXT NOT NULL,
    "as_of" DATE NOT NULL,
    "field" TEXT NOT NULL,
    "dc_code" TEXT NOT NULL,
    "combined_into" TEXT,
    "rejected_value" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "as_of", "field", "dc_code")
);
CREATE INDEX IF NOT EXISTS ix_fundamentals_reason_codes_code ON "fundamentals_reason_codes" ("dc_code");

-- [extract] fundamentals_employees  (pk: ticker, as_of)
-- Employee headcount, parsed out of the 10-K BODY TEXT (there is no GAAP concept for it and
-- US filers essentially never tag `dei:EntityNumberOfEmployees`). Its own table because the
-- source is prose: in the wide table one failed regex would fail the whole snapshot, and a
-- text-parsed number sitting among 67 XBRL-sourced columns reads as if it were one.
--
-- Disclosed ANNUALLY, so `as_of` is a 10-K (or 10-K/A) filing date and a consumer
-- forward-fills into the interim quarters -- `build_history.carry_latest_known` is that
-- alignment. `employees` keeps its tier and authority in the KPI catalogue; it is only out
-- of the wide table's column contract.

CREATE TABLE IF NOT EXISTS "fundamentals_employees" (
    "ticker" TEXT NOT NULL,
    "as_of" DATE NOT NULL,
    "employees" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "as_of")
);

-- [extract] fundamentals_facts  (pk: ticker, accession_number, field, duration_type, period_end)
-- One row per catalogue FIELD per period per filing, resolved from the filer's own XBRL
-- calculation linkbase. STRICTLY AS-FILED: no derived quarter is ever written here (Q4 =
-- FY - YTD9 happens in memory during the history build), and amendments append rather than
-- overwrite -- so `filing_date <= D` answers "what was knowable on D" exactly.
--
-- THE KEY IS THE CALENDAR WINDOW, NOT THE FISCAL LABEL. edgartools tags a 10-K's current year
-- and its first comparative with the SAME `fiscal_year`, so the original PK
-- (fiscal_year, fiscal_period, duration_type) collided them and the upsert dedup dropped one,
-- with frame order deciding which. Measured over 337,190 swept facts: 18,604 rows (5.5%) lost,
-- 16,340 of those collisions holding two DIFFERENT values, and 1,522 ANNUAL facts gone --
-- concentrated in the non-calendar filers (KR 25%, COST 24.5%, CSCO 21%, JNJ 20%, AAPL 18%).
-- AAPL's FY2025 10-K kept FY2023 and FY2024 and dropped FY2025, i.e. the FY fact that is the
-- primary Q4 input. Keyed on `period_end` the same sweep loses 3 rows (0.001%), and those are
-- the one case `periods._latest_per_window` already exists to collapse.
--
-- `period_end` is therefore NOT NULL. A reason-coded row (a field the filing tags nowhere) has
-- no period of its own and falls back to the filing's `period_of_report` -- see `_period_end`.
-- `fiscal_year` / `fiscal_period` are PAYLOAD: periods.py selects every input by calendar
-- window and its own docstring records why ("Nothing in this module reads `fiscal_period`").

CREATE TABLE IF NOT EXISTS "fundamentals_facts" (
    "ticker" TEXT NOT NULL,
    "accession_number" TEXT NOT NULL,
    "field" TEXT NOT NULL,
    "duration_type" TEXT NOT NULL,
    "period_end" DATE NOT NULL,
    "fiscal_year" BIGINT,
    "fiscal_period" TEXT,
    "cik" TEXT,
    "form" TEXT,
    "filing_date" DATE,
    "is_amendment" BOOLEAN,
    "period_of_report" DATE,
    "regime" TEXT,
    "period_start" DATE,
    "period_days" BIGINT,
    "value" DOUBLE PRECISION,
    "unit" TEXT,
    "decimals" TEXT,
    "resolution_method" TEXT,
    "source_concept" TEXT,
    "roll_up_children" TEXT,
    "root_anchor" TEXT,
    "adjustment" TEXT,
    "role_uri" TEXT,
    "is_extension" BOOLEAN,
    "dc_code" TEXT,
    PRIMARY KEY ("ticker", "accession_number", "field", "duration_type", "period_end")
);
CREATE INDEX IF NOT EXISTS ix_fundamentals_facts_filing_date ON "fundamentals_facts" ("filing_date");
CREATE INDEX IF NOT EXISTS ix_fundamentals_facts_field ON "fundamentals_facts" ("ticker", "field");

-- [extract] earnings_surprises  (pk: ticker, earnings_date)

CREATE TABLE IF NOT EXISTS "earnings_surprises" (
    "ticker" TEXT NOT NULL,
    "earnings_date" TIMESTAMP NOT NULL,
    "eps_estimate" DOUBLE PRECISION,
    "eps_actual" DOUBLE PRECISION,
    "surprise_pct" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "earnings_date")
);

-- [extract] pension_facts  (pk: cik, tag, ddate, qtrs)

CREATE TABLE IF NOT EXISTS "pension_facts" (
    "cik" TEXT NOT NULL,
    "ticker" TEXT,
    "tag" TEXT NOT NULL,
    "ddate" DATE NOT NULL,
    "qtrs" BIGINT NOT NULL,
    "uom" TEXT,
    "value" DOUBLE PRECISION,
    "adsh" TEXT,
    "filed" DATE,
    "form" TEXT,
    "fy" TEXT,
    "fp" TEXT,
    "quarter" TEXT,
    PRIMARY KEY ("cik", "tag", "ddate", "qtrs")
);
CREATE INDEX IF NOT EXISTS ix_pension_facts_ticker ON "pension_facts" ("ticker");

-- [extract] notes_num  (pk: adsh, tag, ddate, qtrs)

CREATE TABLE IF NOT EXISTS "notes_num" (
    "cik" TEXT,
    "ticker" TEXT,
    "adsh" TEXT NOT NULL,
    "tag" TEXT NOT NULL,
    "ddate" DATE NOT NULL,
    "qtrs" BIGINT NOT NULL,
    "uom" TEXT,
    "value" DOUBLE PRECISION,
    "footnote" TEXT,
    "form" TEXT,
    "fy" TEXT,
    "fp" TEXT,
    "filed" DATE,
    "period" TEXT,
    PRIMARY KEY ("adsh", "tag", "ddate", "qtrs")
);
CREATE INDEX IF NOT EXISTS ix_notes_num_ticker ON "notes_num" ("ticker");

-- [extract] notes_text  (pk: adsh, tag, ddate, qtrs)

CREATE TABLE IF NOT EXISTS "notes_text" (
    "cik" TEXT,
    "ticker" TEXT,
    "adsh" TEXT NOT NULL,
    "tag" TEXT NOT NULL,
    "ddate" DATE NOT NULL,
    "qtrs" BIGINT NOT NULL,
    "txtlen" BIGINT,
    "escaped" TEXT,
    "value" TEXT,
    "footnote" TEXT,
    "form" TEXT,
    "fy" TEXT,
    "fp" TEXT,
    "filed" DATE,
    "period" TEXT,
    PRIMARY KEY ("adsh", "tag", "ddate", "qtrs")
);
CREATE INDEX IF NOT EXISTS ix_notes_text_ticker ON "notes_text" ("ticker");

-- [extract] sec13f_hr  (pk: cik, period, ticker, cusip)

CREATE TABLE IF NOT EXISTS "sec13f_hr" (
    "cik" TEXT NOT NULL,
    "period" TIMESTAMP NOT NULL,
    "filing_date" TIMESTAMP,
    "ticker" TEXT NOT NULL,
    "cusip" TEXT NOT NULL,
    "shares" BIGINT,
    "value_usd" DOUBLE PRECISION,
    "call_shares" BIGINT,
    "call_value" DOUBLE PRECISION,
    "put_shares" BIGINT,
    "put_value" DOUBLE PRECISION,
    "debt_prn" BIGINT,
    "debt_value" DOUBLE PRECISION,
    "other_value" DOUBLE PRECISION,
    "quarter" TEXT,
    PRIMARY KEY ("cik", "period", "ticker", "cusip")
);

-- [extract] insider_transactions  (pk: accession_number, security_type, transaction_sk)

CREATE TABLE IF NOT EXISTS "insider_transactions" (
    "accession_number" TEXT NOT NULL,
    "security_type" TEXT NOT NULL,
    "transaction_sk" TEXT NOT NULL,
    "ticker" TEXT,
    "issuer_cik" TEXT,
    "issuer_name" TEXT,
    "owner_cik" TEXT,
    "owner_name" TEXT,
    "is_director" DOUBLE PRECISION,
    "is_officer" DOUBLE PRECISION,
    "is_ten_pct_owner" DOUBLE PRECISION,
    "is_other" DOUBLE PRECISION,
    "officer_title" TEXT,
    "document_type" TEXT,
    "transaction_date" DATE,
    "filing_date" DATE,
    "period_of_report" DATE,
    "security_title" TEXT,
    "transaction_code" TEXT,
    "acquired_disposed" TEXT,
    "shares" DOUBLE PRECISION,
    "price_per_share" DOUBLE PRECISION,
    "value_usd" DOUBLE PRECISION,
    "shares_owned_after" DOUBLE PRECISION,
    "direct_indirect" TEXT,
    "quarter" TEXT,
    PRIMARY KEY ("accession_number", "security_type", "transaction_sk")
);
CREATE INDEX IF NOT EXISTS ix_insider_transactions_ticker ON "insider_transactions" ("ticker");
CREATE INDEX IF NOT EXISTS ix_insider_transactions_transaction_date ON "insider_transactions" ("transaction_date");

-- [extract] sec_13d  (pk: ticker, accession_number, rp_seq)

CREATE TABLE IF NOT EXISTS "sec_13d" (
    "ticker" TEXT NOT NULL,
    "cik" TEXT,
    "accession_number" TEXT NOT NULL,
    "form" TEXT,
    "filing_date" DATE,
    "rp_seq" BIGINT NOT NULL,
    "is_amendment" DOUBLE PRECISION,
    "amendment_number" DOUBLE PRECISION,
    "cusip" TEXT,
    "issuer_name" TEXT,
    "date_of_event" DATE,
    "has_structured_data" DOUBLE PRECISION,
    "reporting_person_name" TEXT,
    "reporting_person_cik" TEXT,
    "reporting_person_citizenship" TEXT,
    "type_of_reporting_person" TEXT,
    "is_group_member" TEXT,
    "sole_voting_power" DOUBLE PRECISION,
    "shared_voting_power" DOUBLE PRECISION,
    "sole_dispositive_power" DOUBLE PRECISION,
    "shared_dispositive_power" DOUBLE PRECISION,
    "aggregate_amount" DOUBLE PRECISION,
    "percent_of_class" DOUBLE PRECISION,
    "item3_source_of_funds" TEXT,
    "item4_purpose_of_transaction" TEXT,
    "item5_interest_in_securities" TEXT,
    "item6_contracts_understandings" TEXT,
    "primary_document" TEXT,
    "doc_url" TEXT,
    PRIMARY KEY ("ticker", "accession_number", "rp_seq")
);
CREATE INDEX IF NOT EXISTS ix_sec_13d_filing_date ON "sec_13d" ("filing_date");

-- [extract] sec_13d_transactions  (pk: ticker, accession_number, trade_seq)

CREATE TABLE IF NOT EXISTS "sec_13d_transactions" (
    "ticker" TEXT NOT NULL,
    "cik" TEXT,
    "accession_number" TEXT NOT NULL,
    "filing_date" DATE,
    "trade_seq" BIGINT NOT NULL,
    "reporting_person_name" TEXT,
    "trade_date" DATE,
    "transaction_type" TEXT,
    "quantity" DOUBLE PRECISION,
    "price_per_share" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "accession_number", "trade_seq")
);
CREATE INDEX IF NOT EXISTS ix_sec_13d_transactions_filing_date ON "sec_13d_transactions" ("filing_date");

-- [extract] def14a_llm  (pk: ticker, accession_number)

CREATE TABLE IF NOT EXISTS "def14a_llm" (
    "ticker" TEXT NOT NULL,
    "as_of" TIMESTAMP,
    "period" TIMESTAMP,
    "accession_number" TEXT NOT NULL,
    "company_name" TEXT,
    "fiscal_year_extract" BIGINT,
    "n_directors" BIGINT,
    "board_size" BIGINT,
    "avg_director_age" DOUBLE PRECISION,
    "avg_board_tenure" DOUBLE PRECISION,
    "pct_independent_directors" DOUBLE PRECISION,
    "pct_female_directors" DOUBLE PRECISION,
    "avg_other_public_boards" DOUBLE PRECISION,
    "ceo_name_proxy" TEXT,
    "ceo_age" BIGINT,
    "ceo_since_year" BIGINT,
    "ceo_is_founder" DOUBLE PRECISION,
    "ceo_is_board_chair" DOUBLE PRECISION,
    "ceo_salary" DOUBLE PRECISION,
    "ceo_bonus" DOUBLE PRECISION,
    "ceo_stock_awards" DOUBLE PRECISION,
    "ceo_option_awards" DOUBLE PRECISION,
    "ceo_non_equity_incentive" DOUBLE PRECISION,
    "ceo_all_other_comp" DOUBLE PRECISION,
    "ceo_total_comp" DOUBLE PRECISION,
    "ceo_equity_pay_pct" DOUBLE PRECISION,
    "n_neos" BIGINT,
    "total_neo_comp" DOUBLE PRECISION,
    "insider_ownership_pct" DOUBLE PRECISION,
    "ceo_ownership_pct" DOUBLE PRECISION,
    "n_five_percent_holders" BIGINT,
    "independent_chair" DOUBLE PRECISION,
    "lead_independent_director" DOUBLE PRECISION,
    "classified_board" DOUBLE PRECISION,
    "dual_class_shares" DOUBLE PRECISION,
    "poison_pill" DOUBLE PRECISION,
    "majority_voting" DOUBLE PRECISION,
    "say_on_pay_support_pct" DOUBLE PRECISION,
    "ceo_pay_ratio" DOUBLE PRECISION,
    "median_employee_pay" DOUBLE PRECISION,
    "auditor_fees" DOUBLE PRECISION,
    "def14a_json" TEXT,
    "n_technology_directors" DOUBLE PRECISION,
    "pct_technology_directors" DOUBLE PRECISION,
    "technology_committee" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "accession_number")
);
CREATE INDEX IF NOT EXISTS ix_def14a_llm_as_of ON "def14a_llm" ("as_of");

-- [extract] sec_def14a  (pk: ticker, accession_number)

CREATE TABLE IF NOT EXISTS "sec_def14a" (
    "ticker" TEXT NOT NULL,
    "cik" TEXT,
    "accession_number" TEXT NOT NULL,
    "form" TEXT,
    "filing_date" DATE,
    "period_of_report" DATE,
    "company_name" TEXT,
    "has_xbrl" DOUBLE PRECISION,
    "has_individual_executive_data" DOUBLE PRECISION,
    "peo_name" TEXT,
    "peo_total_comp" DOUBLE PRECISION,
    "peo_actually_paid_comp" DOUBLE PRECISION,
    "neo_avg_total_comp" DOUBLE PRECISION,
    "neo_avg_actually_paid_comp" DOUBLE PRECISION,
    "total_shareholder_return" DOUBLE PRECISION,
    "peer_group_tsr" DOUBLE PRECISION,
    "net_income" DOUBLE PRECISION,
    "company_selected_measure_name" TEXT,
    "company_selected_measure_value" DOUBLE PRECISION,
    "insider_trading_policy_adopted" DOUBLE PRECISION,
    "award_timing_mnpi_considered" DOUBLE PRECISION,
    "award_dates_predetermined" DOUBLE PRECISION,
    "mnpi_disclosure_timed_for_comp_value" DOUBLE PRECISION,
    "ceo_pay_ratio_ceo_comp" DOUBLE PRECISION,
    "ceo_pay_ratio_median_employee_comp" DOUBLE PRECISION,
    "ceo_pay_ratio" DOUBLE PRECISION,
    "auditor_name" TEXT,
    "audit_fiscal_year_current" DOUBLE PRECISION,
    "audit_fiscal_year_prior" DOUBLE PRECISION,
    "audit_fees_current" DOUBLE PRECISION,
    "audit_fees_prior" DOUBLE PRECISION,
    "audit_related_fees_current" DOUBLE PRECISION,
    "audit_related_fees_prior" DOUBLE PRECISION,
    "tax_fees_current" DOUBLE PRECISION,
    "tax_fees_prior" DOUBLE PRECISION,
    "other_fees_current" DOUBLE PRECISION,
    "other_fees_prior" DOUBLE PRECISION,
    "total_fees_current" DOUBLE PRECISION,
    "total_fees_prior" DOUBLE PRECISION,
    "n_voting_proposals" DOUBLE PRECISION,
    "n_say_on_pay_proposals" DOUBLE PRECISION,
    "n_director_election_proposals" DOUBLE PRECISION,
    "n_auditor_ratification_proposals" DOUBLE PRECISION,
    "n_equity_plan_proposals" DOUBLE PRECISION,
    "n_shareholder_proposals" DOUBLE PRECISION,
    "n_board_against_recommendations" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "accession_number")
);
CREATE INDEX IF NOT EXISTS ix_sec_def14a_filing_date ON "sec_def14a" ("filing_date");

-- [extract] sec_def14a_executive_comp  (pk: ticker, accession_number, name, year)

CREATE TABLE IF NOT EXISTS "sec_def14a_executive_comp" (
    "ticker" TEXT NOT NULL,
    "cik" TEXT,
    "accession_number" TEXT NOT NULL,
    "filing_date" DATE,
    "name" TEXT NOT NULL,
    "title" TEXT,
    "year" DOUBLE PRECISION NOT NULL,
    "salary" DOUBLE PRECISION,
    "bonus" DOUBLE PRECISION,
    "stock_awards" DOUBLE PRECISION,
    "option_awards" DOUBLE PRECISION,
    "non_equity_incentive" DOUBLE PRECISION,
    "pension_change" DOUBLE PRECISION,
    "other_compensation" DOUBLE PRECISION,
    "total" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "accession_number", "name", "year")
);
CREATE INDEX IF NOT EXISTS ix_sec_def14a_executive_comp_filing_date ON "sec_def14a_executive_comp" ("filing_date");

-- [extract] sec_def14a_director_comp  (pk: ticker, accession_number, name)

CREATE TABLE IF NOT EXISTS "sec_def14a_director_comp" (
    "ticker" TEXT NOT NULL,
    "cik" TEXT,
    "accession_number" TEXT NOT NULL,
    "filing_date" DATE,
    "name" TEXT NOT NULL,
    "fees_earned" DOUBLE PRECISION,
    "stock_awards" DOUBLE PRECISION,
    "option_awards" DOUBLE PRECISION,
    "non_equity_incentive" DOUBLE PRECISION,
    "pension_change" DOUBLE PRECISION,
    "other_compensation" DOUBLE PRECISION,
    "total" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "accession_number", "name")
);
CREATE INDEX IF NOT EXISTS ix_sec_def14a_director_comp_filing_date ON "sec_def14a_director_comp" ("filing_date");

-- [extract] sec_def14a_ownership  (pk: ticker, accession_number, holder_name, holder_type)

CREATE TABLE IF NOT EXISTS "sec_def14a_ownership" (
    "ticker" TEXT NOT NULL,
    "cik" TEXT,
    "accession_number" TEXT NOT NULL,
    "filing_date" DATE,
    "holder_name" TEXT NOT NULL,
    "holder_type" TEXT NOT NULL,
    "shares" DOUBLE PRECISION,
    "percent_of_class" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "accession_number", "holder_name", "holder_type")
);
CREATE INDEX IF NOT EXISTS ix_sec_def14a_ownership_filing_date ON "sec_def14a_ownership" ("filing_date");

-- [extract] sec_def14a_votes  (pk: ticker, accession_number, proposal_number)

CREATE TABLE IF NOT EXISTS "sec_def14a_votes" (
    "ticker" TEXT NOT NULL,
    "cik" TEXT,
    "accession_number" TEXT NOT NULL,
    "filing_date" DATE,
    "proposal_number" DOUBLE PRECISION NOT NULL,
    "description" TEXT,
    "board_recommendation" TEXT,
    "proposal_type" TEXT,
    PRIMARY KEY ("ticker", "accession_number", "proposal_number")
);
CREATE INDEX IF NOT EXISTS ix_sec_def14a_votes_filing_date ON "sec_def14a_votes" ("filing_date");

-- [extract] sec_8k  (pk: ticker, accession_number, item)

CREATE TABLE IF NOT EXISTS "sec_8k" (
    "ticker" TEXT NOT NULL,
    "cik" TEXT,
    "accession_number" TEXT NOT NULL,
    "form" TEXT,
    "filing_date" DATE,
    "period_of_report" DATE,
    "n_items" BIGINT,
    "is_amendment" DOUBLE PRECISION,
    "has_earnings" DOUBLE PRECISION,
    "has_press_release" DOUBLE PRECISION,
    "primary_document" TEXT,
    "item" TEXT NOT NULL,
    "item_tag" TEXT,
    "item_text" TEXT,
    PRIMARY KEY ("ticker", "accession_number", "item")
);
CREATE INDEX IF NOT EXISTS ix_sec_8k_filing_date ON "sec_8k" ("filing_date");

-- [extract] sec_filing_text  (pk: ticker, accession_number, section)

CREATE TABLE IF NOT EXISTS "sec_filing_text" (
    "ticker" TEXT NOT NULL,
    "cik" TEXT,
    "accession_number" TEXT NOT NULL,
    "form" TEXT,
    "filed" DATE,
    "period_of_report" DATE,
    "section" TEXT NOT NULL,
    "text" TEXT,
    "n_words" BIGINT,
    PRIMARY KEY ("ticker", "accession_number", "section")
);
CREATE INDEX IF NOT EXISTS ix_sec_filing_text_filed ON "sec_filing_text" ("filed");

-- [extract] google_trends  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "google_trends" (
    "date" TIMESTAMP NOT NULL,
    "ticker" TEXT NOT NULL,
    "search_interest" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "date")
);

-- [extract] wiki_pageviews  (pk: ticker, date)

CREATE TABLE IF NOT EXISTS "wiki_pageviews" (
    "date" TIMESTAMP NOT NULL,
    "ticker" TEXT NOT NULL,
    "pageviews" DOUBLE PRECISION,
    PRIMARY KEY ("ticker", "date")
);

-- [extract] earnings_call_sections  (pk: ticker, quarter, tag)

CREATE TABLE IF NOT EXISTS "earnings_call_sections" (
    "ticker" TEXT NOT NULL,
    "quarter" TEXT NOT NULL,
    "tag" TEXT NOT NULL,
    "as_of" DATE,
    "url" TEXT,
    "text" TEXT,
    PRIMARY KEY ("ticker", "quarter", "tag")
);
CREATE INDEX IF NOT EXISTS ix_earnings_call_sections_as_of ON "earnings_call_sections" ("as_of");

-- [extract] earnings_call_sentiment  (pk: ticker, quarter, tag)

CREATE TABLE IF NOT EXISTS "earnings_call_sentiment" (
    "ticker" TEXT NOT NULL,
    "quarter" TEXT NOT NULL,
    "tag" TEXT NOT NULL,
    "as_of" DATE,
    "sent_pos" DOUBLE PRECISION,
    "sent_neg" DOUBLE PRECISION,
    "sent_neu" DOUBLE PRECISION,
    "n_words" BIGINT,
    "uncertainty_ratio" DOUBLE PRECISION,
    "model" TEXT,
    PRIMARY KEY ("ticker", "quarter", "tag")
);
CREATE INDEX IF NOT EXISTS ix_earnings_call_sentiment_as_of ON "earnings_call_sentiment" ("as_of");

-- [extract] earning_calls_embedding  (pk: ticker, quarter, seq)

CREATE TABLE IF NOT EXISTS "earning_calls_embedding" (
    "ticker" TEXT NOT NULL,
    "quarter" TEXT NOT NULL,
    "seq" BIGINT NOT NULL,
    "section" TEXT,
    "tag" TEXT,
    "exchange_idx" BIGINT,
    "answer_idx" BIGINT,
    "person" TEXT,
    "text" TEXT,
    "as_of" TEXT,
    "model" TEXT,
    "run_at" TEXT,
    "embedding" DOUBLE PRECISION[],
    PRIMARY KEY ("ticker", "quarter", "seq")
);

-- SKIPPED (no live schema and no previous DDL): notes_embedding

-- SKIPPED (no live schema and no previous DDL): ticker_descriptions

-- [extract] ticker_embeddings  (pk: ticker)

CREATE TABLE IF NOT EXISTS "ticker_embeddings" (
    "ticker" TEXT NOT NULL,
    "embedding" DOUBLE PRECISION[],
    PRIMARY KEY ("ticker")
);

-- [aggregate] cube  (pk: ticker, date, target_horizon) -- CARRIED OVER: not present in the database that generated this file, so its previous DDL is preserved verbatim.

CREATE TABLE IF NOT EXISTS "cube" (
    "date" TIMESTAMP NOT NULL,
    "ticker" TEXT NOT NULL,
    "target_rank" DOUBLE PRECISION,
    "target_zscore" DOUBLE PRECISION,
    "target_horizon" BIGINT NOT NULL,
    "mom_12_1" DOUBLE PRECISION,
    "rev_5" DOUBLE PRECISION,
    "rev_21" DOUBLE PRECISION,
    "vol_21" DOUBLE PRECISION,
    "vol_63" DOUBLE PRECISION,
    "ma_ratio_50" DOUBLE PRECISION,
    "ma_ratio_200" DOUBLE PRECISION,
    "high_prox_252" DOUBLE PRECISION,
    "gap_21" DOUBLE PRECISION,
    "range_21" DOUBLE PRECISION,
    "peer_mom_63" DOUBLE PRECISION,
    "max_21" DOUBLE PRECISION,
    "ret_skew_126" DOUBLE PRECISION,
    "downside_vol_63" DOUBLE PRECISION,
    "idio_vol_63" DOUBLE PRECISION,
    "dollar_volume_63" DOUBLE PRECISION,
    "amihud_63" DOUBLE PRECISION,
    "rel_volume_5_63" DOUBLE PRECISION,
    "signed_vol_63" DOUBLE PRECISION,
    "volume_trend_63" DOUBLE PRECISION,
    "volume_cv_63" DOUBLE PRECISION,
    "seasonal_h30" DOUBLE PRECISION,
    "seasonal_h60" DOUBLE PRECISION,
    "seasonal_h90" DOUBLE PRECISION,
    "tax_loss_pressure" DOUBLE PRECISION,
    "macd" DOUBLE PRECISION,
    "macd_hist" DOUBLE PRECISION,
    "rsi_14" DOUBLE PRECISION,
    "atr_14" DOUBLE PRECISION,
    "f_pension_funded_ratio_vs_peers" DOUBLE PRECISION,
    "f_pension_funded_ratio_xs" DOUBLE PRECISION,
    "f_pension_retirement_liability_vs_peers" DOUBLE PRECISION,
    "f_pension_retirement_liability_xs" DOUBLE PRECISION,
    "f_earnings_yield_vs_peers" DOUBLE PRECISION,
    "f_earnings_yield_xs" DOUBLE PRECISION,
    "f_sales_yield_vs_peers" DOUBLE PRECISION,
    "f_sales_yield_xs" DOUBLE PRECISION,
    "f_book_yield_vs_peers" DOUBLE PRECISION,
    "f_book_yield_xs" DOUBLE PRECISION,
    "f_fcf_yield_vs_peers" DOUBLE PRECISION,
    "f_fcf_yield_xs" DOUBLE PRECISION,
    "f_pension_overhang_leverage_vs_peers" DOUBLE PRECISION,
    "f_pension_overhang_leverage_xs" DOUBLE PRECISION,
    "f_pbo_to_mcap_vs_peers" DOUBLE PRECISION,
    "f_pbo_to_mcap_xs" DOUBLE PRECISION,
    "f_pension_underfunding_to_mcap_vs_peers" DOUBLE PRECISION,
    "f_pension_underfunding_to_mcap_xs" DOUBLE PRECISION,
    "f_ebitda_to_ev_vs_peers" DOUBLE PRECISION,
    "f_ebitda_to_ev_xs" DOUBLE PRECISION,
    "f_fcf_to_ev_vs_peers" DOUBLE PRECISION,
    "f_fcf_to_ev_xs" DOUBLE PRECISION,
    "f_altman_z_vs_peers" DOUBLE PRECISION,
    "f_altman_z_xs" DOUBLE PRECISION,
    "f_pegy_vs_peers" DOUBLE PRECISION,
    "f_pegy_xs" DOUBLE PRECISION,
    "f_ffo_yield_vs_peers" DOUBLE PRECISION,
    "f_ffo_yield_xs" DOUBLE PRECISION,
    "f_implied_cap_rate_vs_peers" DOUBLE PRECISION,
    "f_implied_cap_rate_xs" DOUBLE PRECISION,
    "f_ebitdax_to_ev_vs_peers" DOUBLE PRECISION,
    "f_ebitdax_to_ev_xs" DOUBLE PRECISION,
    "f_grossMargins_vs_peers" DOUBLE PRECISION,
    "f_grossMargins_xs" DOUBLE PRECISION,
    "f_operatingMargins_vs_peers" DOUBLE PRECISION,
    "f_operatingMargins_xs" DOUBLE PRECISION,
    "f_profitMargins_vs_peers" DOUBLE PRECISION,
    "f_profitMargins_xs" DOUBLE PRECISION,
    "f_returnOnEquity_vs_peers" DOUBLE PRECISION,
    "f_returnOnEquity_xs" DOUBLE PRECISION,
    "f_debtToEquity_vs_peers" DOUBLE PRECISION,
    "f_debtToEquity_xs" DOUBLE PRECISION,
    "f_revenueGrowth_vs_peers" DOUBLE PRECISION,
    "f_revenueGrowth_xs" DOUBLE PRECISION,
    "f_earningsGrowth_vs_peers" DOUBLE PRECISION,
    "f_earningsGrowth_xs" DOUBLE PRECISION,
    "f_fcf_margin_vs_peers" DOUBLE PRECISION,
    "f_fcf_margin_xs" DOUBLE PRECISION,
    "f_accruals_vs_peers" DOUBLE PRECISION,
    "f_accruals_xs" DOUBLE PRECISION,
    "f_fcf_growth_vs_peers" DOUBLE PRECISION,
    "f_fcf_growth_xs" DOUBLE PRECISION,
    "f_shares_growth_vs_peers" DOUBLE PRECISION,
    "f_shares_growth_xs" DOUBLE PRECISION,
    "f_gross_margin_chg_vs_peers" DOUBLE PRECISION,
    "f_gross_margin_chg_xs" DOUBLE PRECISION,
    "f_operating_margin_5y_chg_vs_peers" DOUBLE PRECISION,
    "f_operating_margin_5y_chg_xs" DOUBLE PRECISION,
    "f_rd_intensity_vs_peers" DOUBLE PRECISION,
    "f_rd_intensity_xs" DOUBLE PRECISION,
    "f_da_to_capex_vs_peers" DOUBLE PRECISION,
    "f_da_to_capex_xs" DOUBLE PRECISION,
    "f_da_minus_capex_growth_vs_peers" DOUBLE PRECISION,
    "f_da_minus_capex_growth_xs" DOUBLE PRECISION,
    "f_gross_profitability_vs_peers" DOUBLE PRECISION,
    "f_gross_profitability_xs" DOUBLE PRECISION,
    "f_asset_growth_vs_peers" DOUBLE PRECISION,
    "f_asset_growth_xs" DOUBLE PRECISION,
    "f_rule_of_40_vs_peers" DOUBLE PRECISION,
    "f_rule_of_40_xs" DOUBLE PRECISION,
    "f_rpo_growth_vs_peers" DOUBLE PRECISION,
    "f_rpo_growth_xs" DOUBLE PRECISION,
    "f_piotroski_f_score_vs_peers" DOUBLE PRECISION,
    "f_piotroski_f_score_xs" DOUBLE PRECISION,
    "f_q_rev_growth_vs_peers" DOUBLE PRECISION,
    "f_q_rev_growth_xs" DOUBLE PRECISION,
    "f_rev_growth_accel_vs_peers" DOUBLE PRECISION,
    "f_rev_growth_accel_xs" DOUBLE PRECISION,
    "f_q_earnings_growth_vs_peers" DOUBLE PRECISION,
    "f_q_earnings_growth_xs" DOUBLE PRECISION,
    "f_q_margin_vs_ttm_vs_peers" DOUBLE PRECISION,
    "f_q_margin_vs_ttm_xs" DOUBLE PRECISION,
    "f_y_rev_growth_vs_peers" DOUBLE PRECISION,
    "f_y_rev_growth_xs" DOUBLE PRECISION,
    "f_y_rev_growth_accel_vs_peers" DOUBLE PRECISION,
    "f_y_rev_growth_accel_xs" DOUBLE PRECISION,
    "f_y_earnings_growth_vs_peers" DOUBLE PRECISION,
    "f_y_earnings_growth_xs" DOUBLE PRECISION,
    "f_y_margin_vs_ttm_vs_peers" DOUBLE PRECISION,
    "f_y_margin_vs_ttm_xs" DOUBLE PRECISION,
    "f_net_debt_to_ebitda_vs_peers" DOUBLE PRECISION,
    "f_net_debt_to_ebitda_xs" DOUBLE PRECISION,
    "f_interest_coverage_vs_peers" DOUBLE PRECISION,
    "f_interest_coverage_xs" DOUBLE PRECISION,
    "f_current_ratio_vs_peers" DOUBLE PRECISION,
    "f_current_ratio_xs" DOUBLE PRECISION,
    "f_cash_to_debt_vs_peers" DOUBLE PRECISION,
    "f_cash_to_debt_xs" DOUBLE PRECISION,
    "f_refinancing_risk_vs_peers" DOUBLE PRECISION,
    "f_refinancing_risk_xs" DOUBLE PRECISION,
    "f_sga_intensity_vs_peers" DOUBLE PRECISION,
    "f_sga_intensity_xs" DOUBLE PRECISION,
    "f_sga_growth_vs_peers" DOUBLE PRECISION,
    "f_sga_growth_xs" DOUBLE PRECISION,
    "f_operating_leverage_vs_peers" DOUBLE PRECISION,
    "f_operating_leverage_xs" DOUBLE PRECISION,
    "f_acquisition_intensity_vs_peers" DOUBLE PRECISION,
    "f_acquisition_intensity_xs" DOUBLE PRECISION,
    "f_goodwill_growth_vs_peers" DOUBLE PRECISION,
    "f_goodwill_growth_xs" DOUBLE PRECISION,
    "f_sbc_intensity_vs_peers" DOUBLE PRECISION,
    "f_sbc_intensity_xs" DOUBLE PRECISION,
    "f_sbc_to_ocf_vs_peers" DOUBLE PRECISION,
    "f_sbc_to_ocf_xs" DOUBLE PRECISION,
    "f_operating_leverage_elasticity_vs_peers" DOUBLE PRECISION,
    "f_operating_leverage_elasticity_xs" DOUBLE PRECISION,
    "f_margin_expansion_delta_vs_peers" DOUBLE PRECISION,
    "f_margin_expansion_delta_xs" DOUBLE PRECISION,
    "f_nwc_elasticity_vs_peers" DOUBLE PRECISION,
    "f_nwc_elasticity_xs" DOUBLE PRECISION,
    "f_diluted_shares_growth_vs_peers" DOUBLE PRECISION,
    "f_diluted_shares_growth_xs" DOUBLE PRECISION,
    "f_ebit_interest_coverage_vs_peers" DOUBLE PRECISION,
    "f_ebit_interest_coverage_xs" DOUBLE PRECISION,
    "f_intrinsic_yield_vs_peers" DOUBLE PRECISION,
    "f_intrinsic_yield_xs" DOUBLE PRECISION,
    "f_implied_useful_life_vs_peers" DOUBLE PRECISION,
    "f_implied_useful_life_xs" DOUBLE PRECISION,
    "f_useful_life_change_vs_peers" DOUBLE PRECISION,
    "f_useful_life_change_xs" DOUBLE PRECISION,
    "f_asset_age_vs_peers" DOUBLE PRECISION,
    "f_asset_age_xs" DOUBLE PRECISION,
    "f_intangible_amortization_share_vs_peers" DOUBLE PRECISION,
    "f_intangible_amortization_share_xs" DOUBLE PRECISION,
    "f_sbc_to_buyback_vs_peers" DOUBLE PRECISION,
    "f_sbc_to_buyback_xs" DOUBLE PRECISION,
    "f_dso_vs_peers" DOUBLE PRECISION,
    "f_dso_xs" DOUBLE PRECISION,
    "f_dso_change_vs_peers" DOUBLE PRECISION,
    "f_dso_change_xs" DOUBLE PRECISION,
    "f_dpo_vs_peers" DOUBLE PRECISION,
    "f_dpo_xs" DOUBLE PRECISION,
    "f_dpo_change_vs_peers" DOUBLE PRECISION,
    "f_dpo_change_xs" DOUBLE PRECISION,
    "f_dio_vs_peers" DOUBLE PRECISION,
    "f_dio_xs" DOUBLE PRECISION,
    "f_cash_conversion_cycle_vs_peers" DOUBLE PRECISION,
    "f_cash_conversion_cycle_xs" DOUBLE PRECISION,
    "f_net_debt_incl_offbs_to_ebitda_vs_peers" DOUBLE PRECISION,
    "f_net_debt_incl_offbs_to_ebitda_xs" DOUBLE PRECISION,
    "f_beneish_m_score_vs_peers" DOUBLE PRECISION,
    "f_beneish_m_score_xs" DOUBLE PRECISION,
    "f_roic_incl_goodwill_vs_peers" DOUBLE PRECISION,
    "f_roic_incl_goodwill_xs" DOUBLE PRECISION,
    "f_roic_ex_goodwill_vs_peers" DOUBLE PRECISION,
    "f_roic_ex_goodwill_xs" DOUBLE PRECISION,
    "f_goodwill_roic_drag_vs_peers" DOUBLE PRECISION,
    "f_goodwill_roic_drag_xs" DOUBLE PRECISION,
    "f_goodwill_intangibles_to_assets_vs_peers" DOUBLE PRECISION,
    "f_goodwill_intangibles_to_assets_xs" DOUBLE PRECISION,
    "f_goodwill_to_equity_vs_peers" DOUBLE PRECISION,
    "f_goodwill_to_equity_xs" DOUBLE PRECISION,
    "f_goodwill_impairment_intensity_vs_peers" DOUBLE PRECISION,
    "f_goodwill_impairment_intensity_xs" DOUBLE PRECISION,
    "f_sga_elasticity_vs_peers" DOUBLE PRECISION,
    "f_sga_elasticity_xs" DOUBLE PRECISION,
    "f_nonrecurring_pretax_share_vs_peers" DOUBLE PRECISION,
    "f_nonrecurring_pretax_share_xs" DOUBLE PRECISION,
    "f_special_items_intensity_vs_peers" DOUBLE PRECISION,
    "f_special_items_intensity_xs" DOUBLE PRECISION,
    "f_core_profit_margin_vs_peers" DOUBLE PRECISION,
    "f_core_profit_margin_xs" DOUBLE PRECISION,
    "f_core_earnings_yield_vs_peers" DOUBLE PRECISION,
    "f_core_earnings_yield_xs" DOUBLE PRECISION,
    "f_core_operating_margin_vs_peers" DOUBLE PRECISION,
    "f_core_operating_margin_xs" DOUBLE PRECISION,
    "f_adjusted_ebitda_margin_vs_peers" DOUBLE PRECISION,
    "f_adjusted_ebitda_margin_xs" DOUBLE PRECISION,
    "f_capitalized_software_intensity_vs_peers" DOUBLE PRECISION,
    "f_capitalized_software_intensity_xs" DOUBLE PRECISION,
    "f_software_to_revenue_vs_peers" DOUBLE PRECISION,
    "f_software_to_revenue_xs" DOUBLE PRECISION,
    "f_debt_maturity_wall_1y_vs_peers" DOUBLE PRECISION,
    "f_debt_maturity_wall_1y_xs" DOUBLE PRECISION,
    "f_debt_maturity_wall_5y_vs_peers" DOUBLE PRECISION,
    "f_debt_maturity_wall_5y_xs" DOUBLE PRECISION,
    "f_debt_maturity_front_loading_vs_peers" DOUBLE PRECISION,
    "f_debt_maturity_front_loading_xs" DOUBLE PRECISION,
    "f_cash_tax_rate_vs_peers" DOUBLE PRECISION,
    "f_cash_tax_rate_xs" DOUBLE PRECISION,
    "f_cash_book_tax_gap_vs_peers" DOUBLE PRECISION,
    "f_cash_book_tax_gap_xs" DOUBLE PRECISION,
    "f_valuation_allowance_ratio_vs_peers" DOUBLE PRECISION,
    "f_valuation_allowance_ratio_xs" DOUBLE PRECISION,
    "f_unrecognized_tax_benefits_ratio_vs_peers" DOUBLE PRECISION,
    "f_unrecognized_tax_benefits_ratio_xs" DOUBLE PRECISION,
    "f_option_overhang_vs_peers" DOUBLE PRECISION,
    "f_option_overhang_xs" DOUBLE PRECISION,
    "f_eps_yield_vs_peers" DOUBLE PRECISION,
    "f_eps_yield_xs" DOUBLE PRECISION,
    "f_dps_growth_vs_peers" DOUBLE PRECISION,
    "f_dps_growth_xs" DOUBLE PRECISION,
    "f_nci_income_share_vs_peers" DOUBLE PRECISION,
    "f_nci_income_share_xs" DOUBLE PRECISION,
    "f_equity_method_income_share_vs_peers" DOUBLE PRECISION,
    "f_equity_method_income_share_xs" DOUBLE PRECISION,
    "f_oci_to_net_income_vs_peers" DOUBLE PRECISION,
    "f_oci_to_net_income_xs" DOUBLE PRECISION,
    "f_receivable_allowance_ratio_vs_peers" DOUBLE PRECISION,
    "f_receivable_allowance_ratio_xs" DOUBLE PRECISION,
    "f_reportable_segments_vs_peers" DOUBLE PRECISION,
    "f_reportable_segments_xs" DOUBLE PRECISION,
    "f_lease_asset_intensity_vs_peers" DOUBLE PRECISION,
    "f_lease_asset_intensity_xs" DOUBLE PRECISION,
    "f_lifo_reserve_ratio_vs_peers" DOUBLE PRECISION,
    "f_lifo_reserve_ratio_xs" DOUBLE PRECISION,
    "f_non_service_pension_to_revenue_vs_peers" DOUBLE PRECISION,
    "f_non_service_pension_to_revenue_xs" DOUBLE PRECISION,
    "f_excise_tax_to_revenue_vs_peers" DOUBLE PRECISION,
    "f_excise_tax_to_revenue_xs" DOUBLE PRECISION,
    "f_aro_to_mcap_vs_peers" DOUBLE PRECISION,
    "f_aro_to_mcap_xs" DOUBLE PRECISION,
    "f_intangible_asset_age_vs_peers" DOUBLE PRECISION,
    "f_intangible_asset_age_xs" DOUBLE PRECISION,
    "f_goodwill_acquired_intensity_vs_peers" DOUBLE PRECISION,
    "f_goodwill_acquired_intensity_xs" DOUBLE PRECISION,
    "f_earnings_yield_vs_hist" DOUBLE PRECISION,
    "f_sales_yield_vs_hist" DOUBLE PRECISION,
    "f_book_yield_vs_hist" DOUBLE PRECISION,
    "f_fcf_yield_vs_hist" DOUBLE PRECISION,
    "f_ebitda_to_ev_vs_hist" DOUBLE PRECISION,
    "f_fcf_to_ev_vs_hist" DOUBLE PRECISION,
    "f_ffo_yield_vs_hist" DOUBLE PRECISION,
    "f_intrinsic_yield_vs_hist" DOUBLE PRECISION,
    "f_core_earnings_yield_vs_hist" DOUBLE PRECISION,
    "f_profitable" DOUBLE PRECISION,
    "f_fcf_positive" DOUBLE PRECISION,
    "f_negative_equity" DOUBLE PRECISION,
    "f_hyper_growth" DOUBLE PRECISION,
    "f_effective_tax_rate_vs_peers" DOUBLE PRECISION,
    "f_effective_tax_rate_xs" DOUBLE PRECISION,
    "f_accruals_ratio_vs_peers" DOUBLE PRECISION,
    "f_accruals_ratio_xs" DOUBLE PRECISION,
    "f_asset_turnover_vs_peers" DOUBLE PRECISION,
    "f_asset_turnover_xs" DOUBLE PRECISION,
    "f_capex_intensity_vs_peers" DOUBLE PRECISION,
    "f_capex_intensity_xs" DOUBLE PRECISION,
    "f_capex_to_dep_vs_peers" DOUBLE PRECISION,
    "f_capex_to_dep_xs" DOUBLE PRECISION,
    "f_payout_ratio_vs_peers" DOUBLE PRECISION,
    "f_payout_ratio_xs" DOUBLE PRECISION,
    "f_buyback_intensity_vs_peers" DOUBLE PRECISION,
    "f_buyback_intensity_xs" DOUBLE PRECISION,
    "f_days_sales_outstanding_vs_peers" DOUBLE PRECISION,
    "f_days_sales_outstanding_xs" DOUBLE PRECISION,
    "f_days_inventory_outstanding_vs_peers" DOUBLE PRECISION,
    "f_days_inventory_outstanding_xs" DOUBLE PRECISION,
    "f_days_payable_outstanding_vs_peers" DOUBLE PRECISION,
    "f_days_payable_outstanding_xs" DOUBLE PRECISION,
    "f_roic_vs_peers" DOUBLE PRECISION,
    "f_roic_xs" DOUBLE PRECISION,
    "f_earnings_quality_vs_peers" DOUBLE PRECISION,
    "f_earnings_quality_xs" DOUBLE PRECISION,
    "f_reinvestment_rate_vs_peers" DOUBLE PRECISION,
    "f_reinvestment_rate_xs" DOUBLE PRECISION,
    "f_sustainable_growth_rate_vs_peers" DOUBLE PRECISION,
    "f_sustainable_growth_rate_xs" DOUBLE PRECISION,
    "f_fixed_cost_coverage_margin_vs_peers" DOUBLE PRECISION,
    "f_fixed_cost_coverage_margin_xs" DOUBLE PRECISION,
    "f_gmroi_vs_peers" DOUBLE PRECISION,
    "f_gmroi_xs" DOUBLE PRECISION,
    "f_bad_debt_intensity_vs_peers" DOUBLE PRECISION,
    "f_bad_debt_intensity_xs" DOUBLE PRECISION,
    "f_net_interest_margin_vs_peers" DOUBLE PRECISION,
    "f_net_interest_margin_xs" DOUBLE PRECISION,
    "f_efficiency_ratio_vs_peers" DOUBLE PRECISION,
    "f_efficiency_ratio_xs" DOUBLE PRECISION,
    "f_provision_rate_vs_peers" DOUBLE PRECISION,
    "f_provision_rate_xs" DOUBLE PRECISION,
    "f_loan_to_deposit_vs_peers" DOUBLE PRECISION,
    "f_loan_to_deposit_xs" DOUBLE PRECISION,
    "f_bank_roa_vs_peers" DOUBLE PRECISION,
    "f_bank_roa_xs" DOUBLE PRECISION,
    "f_bank_operating_margin_vs_peers" DOUBLE PRECISION,
    "f_bank_operating_margin_xs" DOUBLE PRECISION,
    "f_reserve_coverage_velocity_vs_peers" DOUBLE PRECISION,
    "f_reserve_coverage_velocity_xs" DOUBLE PRECISION,
    "f_tier1_capital_ratio_vs_peers" DOUBLE PRECISION,
    "f_tier1_capital_ratio_xs" DOUBLE PRECISION,
    "f_deposit_stickiness_vs_peers" TEXT,
    "f_deposit_stickiness_xs" DOUBLE PRECISION,
    "f_nii_growth_vs_peers" DOUBLE PRECISION,
    "f_nii_growth_xs" DOUBLE PRECISION,
    "f_loan_growth_vs_peers" DOUBLE PRECISION,
    "f_loan_growth_xs" DOUBLE PRECISION,
    "f_aoci_to_equity_vs_peers" DOUBLE PRECISION,
    "f_aoci_to_equity_xs" DOUBLE PRECISION,
    "f_htm_unrealized_loss_ratio_vs_peers" DOUBLE PRECISION,
    "f_htm_unrealized_loss_ratio_xs" DOUBLE PRECISION,
    "f_npl_ratio_vs_peers" DOUBLE PRECISION,
    "f_npl_ratio_xs" DOUBLE PRECISION,
    "f_net_charge_off_rate_vs_peers" DOUBLE PRECISION,
    "f_net_charge_off_rate_xs" DOUBLE PRECISION,
    "f_loss_ratio_vs_peers" DOUBLE PRECISION,
    "f_loss_ratio_xs" DOUBLE PRECISION,
    "f_expense_ratio_vs_peers" DOUBLE PRECISION,
    "f_expense_ratio_xs" DOUBLE PRECISION,
    "f_combined_ratio_vs_peers" DOUBLE PRECISION,
    "f_combined_ratio_xs" DOUBLE PRECISION,
    "f_investment_income_ratio_vs_peers" DOUBLE PRECISION,
    "f_investment_income_ratio_xs" DOUBLE PRECISION,
    "f_book_value_growth_vs_peers" DOUBLE PRECISION,
    "f_book_value_growth_xs" DOUBLE PRECISION,
    "f_premium_growth_vs_peers" DOUBLE PRECISION,
    "f_premium_growth_xs" DOUBLE PRECISION,
    "f_float_growth_vs_peers" DOUBLE PRECISION,
    "f_float_growth_xs" DOUBLE PRECISION,
    "f_ffo_margin_vs_peers" DOUBLE PRECISION,
    "f_ffo_margin_xs" DOUBLE PRECISION,
    "f_ffo_payout_vs_peers" DOUBLE PRECISION,
    "f_ffo_payout_xs" DOUBLE PRECISION,
    "f_rental_margin_vs_peers" DOUBLE PRECISION,
    "f_rental_margin_xs" DOUBLE PRECISION,
    "f_affo_margin_vs_peers" DOUBLE PRECISION,
    "f_affo_margin_xs" DOUBLE PRECISION,
    "f_net_debt_to_ebitdare_vs_peers" DOUBLE PRECISION,
    "f_net_debt_to_ebitdare_xs" DOUBLE PRECISION,
    "f_affo_dividend_coverage_vs_peers" DOUBLE PRECISION,
    "f_affo_dividend_coverage_xs" DOUBLE PRECISION,
    "f_exploration_intensity_vs_peers" DOUBLE PRECISION,
    "f_exploration_intensity_xs" DOUBLE PRECISION,
    "f_ddna_intensity_vs_peers" DOUBLE PRECISION,
    "f_ddna_intensity_xs" DOUBLE PRECISION,
    "f_ebitdax_margin_vs_peers" DOUBLE PRECISION,
    "f_ebitdax_margin_xs" DOUBLE PRECISION,
    "f_property_overvaluation_cushion_vs_peers" DOUBLE PRECISION,
    "f_property_overvaluation_cushion_xs" DOUBLE PRECISION,
    "f_deferred_rev_intensity_vs_peers" DOUBLE PRECISION,
    "f_deferred_rev_intensity_xs" DOUBLE PRECISION,
    "f_rpo_coverage_vs_peers" DOUBLE PRECISION,
    "f_rpo_coverage_xs" DOUBLE PRECISION,
    "f_regulatory_asset_ratio_vs_peers" DOUBLE PRECISION,
    "f_regulatory_asset_ratio_xs" DOUBLE PRECISION,
    "f_capex_to_rate_base_vs_peers" DOUBLE PRECISION,
    "f_capex_to_rate_base_xs" DOUBLE PRECISION,
    "f_patent_cliff_vs_peers" DOUBLE PRECISION,
    "f_patent_cliff_xs" DOUBLE PRECISION,
    "f_rd_capitalized_roic_vs_peers" DOUBLE PRECISION,
    "f_rd_capitalized_roic_xs" DOUBLE PRECISION,
    "f_fwd_eps_yield_vs_peers" DOUBLE PRECISION,
    "f_fwd_eps_yield_xs" DOUBLE PRECISION,
    "f_eps_expectation_growth_vs_peers" DOUBLE PRECISION,
    "f_eps_expectation_growth_xs" DOUBLE PRECISION,
    "f_forward_earnings_yield_vs_peers" DOUBLE PRECISION,
    "f_forward_earnings_yield_xs" DOUBLE PRECISION,
    "f_eps_surprise_last_vs_peers" DOUBLE PRECISION,
    "f_eps_surprise_last_xs" DOUBLE PRECISION,
    "f_eps_surprise_4q_avg_vs_peers" DOUBLE PRECISION,
    "f_eps_surprise_4q_avg_xs" DOUBLE PRECISION,
    "f_days_since_earnings" DOUBLE PRECISION,
    "f_ceo_pay_ratio_vs_peers" DOUBLE PRECISION,
    "f_ceo_pay_ratio_xs" DOUBLE PRECISION,
    "f_ceo_equity_pay_pct_vs_peers" DOUBLE PRECISION,
    "f_ceo_equity_pay_pct_xs" DOUBLE PRECISION,
    "f_pct_independent_directors_vs_peers" DOUBLE PRECISION,
    "f_pct_independent_directors_xs" DOUBLE PRECISION,
    "f_pct_female_directors_vs_peers" DOUBLE PRECISION,
    "f_pct_female_directors_xs" DOUBLE PRECISION,
    "f_board_size_vs_peers" DOUBLE PRECISION,
    "f_board_size_xs" DOUBLE PRECISION,
    "f_avg_board_tenure_vs_peers" DOUBLE PRECISION,
    "f_avg_board_tenure_xs" DOUBLE PRECISION,
    "f_say_on_pay_support_vs_peers" DOUBLE PRECISION,
    "f_say_on_pay_support_xs" DOUBLE PRECISION,
    "f_insider_ownership_pct_vs_peers" DOUBLE PRECISION,
    "f_insider_ownership_pct_xs" DOUBLE PRECISION,
    "f_founder_ceo_vs_peers" DOUBLE PRECISION,
    "f_founder_ceo_xs" DOUBLE PRECISION,
    "f_ceo_tenure_vs_peers" DOUBLE PRECISION,
    "f_ceo_tenure_xs" DOUBLE PRECISION,
    "f_ceo_pay_growth_vs_peers" DOUBLE PRECISION,
    "f_ceo_pay_growth_xs" DOUBLE PRECISION,
    "f_ceo_pay_vs_revenue_growth_vs_peers" DOUBLE PRECISION,
    "f_ceo_pay_vs_revenue_growth_xs" DOUBLE PRECISION,
    "f_employee_growth_vs_peers" DOUBLE PRECISION,
    "f_employee_growth_xs" DOUBLE PRECISION,
    "f_revenue_per_employee_vs_peers" DOUBLE PRECISION,
    "f_revenue_per_employee_xs" DOUBLE PRECISION,
    "f_revenue_per_employee_growth_vs_peers" DOUBLE PRECISION,
    "f_revenue_per_employee_growth_xs" DOUBLE PRECISION,
    "f_headcount_elasticity_vs_peers" DOUBLE PRECISION,
    "f_headcount_elasticity_xs" DOUBLE PRECISION,
    "f_dividend_yield_vs_peers" DOUBLE PRECISION,
    "f_dividend_yield_xs" DOUBLE PRECISION,
    "f_dividend_growth_vs_peers" DOUBLE PRECISION,
    "f_dividend_growth_xs" DOUBLE PRECISION,
    "f_dividend_growth_5y_vs_peers" DOUBLE PRECISION,
    "f_dividend_growth_5y_xs" DOUBLE PRECISION,
    "f_dividend_payer_vs_peers" DOUBLE PRECISION,
    "f_dividend_payer_xs" DOUBLE PRECISION,
    "f_dividend_payout_ratio_vs_peers" DOUBLE PRECISION,
    "f_dividend_payout_ratio_xs" DOUBLE PRECISION,
    "f_dividend_coverage_vs_peers" DOUBLE PRECISION,
    "f_dividend_coverage_xs" DOUBLE PRECISION,
    "f_shareholder_yield_vs_peers" DOUBLE PRECISION,
    "f_shareholder_yield_xs" DOUBLE PRECISION,
    "f_inst_holders_vs_peers" DOUBLE PRECISION,
    "f_inst_holders_xs" DOUBLE PRECISION,
    "f_inst_breadth_chg_vs_peers" DOUBLE PRECISION,
    "f_inst_breadth_chg_xs" DOUBLE PRECISION,
    "f_inst_shares_chg_vs_peers" DOUBLE PRECISION,
    "f_inst_shares_chg_xs" DOUBLE PRECISION,
    "f_inst_value_chg_vs_peers" DOUBLE PRECISION,
    "f_inst_value_chg_xs" DOUBLE PRECISION,
    "f_new_buyers_vs_peers" DOUBLE PRECISION,
    "f_new_buyers_xs" DOUBLE PRECISION,
    "f_exiters_vs_peers" DOUBLE PRECISION,
    "f_exiters_xs" DOUBLE PRECISION,
    "f_cluster_buying_vs_peers" DOUBLE PRECISION,
    "f_cluster_buying_xs" DOUBLE PRECISION,
    "f_new_buyer_ratio_vs_peers" DOUBLE PRECISION,
    "f_new_buyer_ratio_xs" DOUBLE PRECISION,
    "f_net_options_ratio_vs_peers" DOUBLE PRECISION,
    "f_net_options_ratio_xs" DOUBLE PRECISION,
    "f_net_options_ratio_chg_vs_peers" DOUBLE PRECISION,
    "f_net_options_ratio_chg_xs" DOUBLE PRECISION,
    "f_inst_concentration_vs_peers" DOUBLE PRECISION,
    "f_inst_concentration_xs" DOUBLE PRECISION,
    "f_inst_ownership_pct_vs_peers" DOUBLE PRECISION,
    "f_inst_ownership_pct_xs" DOUBLE PRECISION,
    "f_inst_value_to_mcap_vs_peers" DOUBLE PRECISION,
    "f_inst_value_to_mcap_xs" DOUBLE PRECISION,
    "f_inst_flow_to_mcap_vs_peers" DOUBLE PRECISION,
    "f_inst_flow_to_mcap_xs" DOUBLE PRECISION,
    "f_super_holders_vs_peers" DOUBLE PRECISION,
    "f_super_holders_xs" DOUBLE PRECISION,
    "f_super_breadth_chg_vs_peers" DOUBLE PRECISION,
    "f_super_breadth_chg_xs" DOUBLE PRECISION,
    "f_super_shares_chg_vs_peers" DOUBLE PRECISION,
    "f_super_shares_chg_xs" DOUBLE PRECISION,
    "f_super_value_chg_vs_peers" DOUBLE PRECISION,
    "f_super_value_chg_xs" DOUBLE PRECISION,
    "f_super_cluster_buying_vs_peers" DOUBLE PRECISION,
    "f_super_cluster_buying_xs" DOUBLE PRECISION,
    "f_super_new_buyer_ratio_vs_peers" DOUBLE PRECISION,
    "f_super_new_buyer_ratio_xs" DOUBLE PRECISION,
    "f_super_value_to_mcap_vs_peers" DOUBLE PRECISION,
    "f_super_value_to_mcap_xs" DOUBLE PRECISION,
    "f_super_flow_to_mcap_vs_peers" DOUBLE PRECISION,
    "f_super_flow_to_mcap_xs" DOUBLE PRECISION,
    "f_insider_net_buy_ratio_vs_peers" DOUBLE PRECISION,
    "f_insider_net_buy_ratio_xs" DOUBLE PRECISION,
    "f_insider_buy_sell_count_ratio_vs_peers" DOUBLE PRECISION,
    "f_insider_buy_sell_count_ratio_xs" DOUBLE PRECISION,
    "f_insider_buy_count_vs_peers" DOUBLE PRECISION,
    "f_insider_buy_count_xs" DOUBLE PRECISION,
    "f_insider_net_buy_to_mcap_vs_peers" DOUBLE PRECISION,
    "f_insider_net_buy_to_mcap_xs" DOUBLE PRECISION,
    "f_short_vol_ratio_vs_peers" DOUBLE PRECISION,
    "f_short_vol_ratio_xs" DOUBLE PRECISION,
    "f_short_vol_ratio_chg_vs_peers" DOUBLE PRECISION,
    "f_short_vol_ratio_chg_xs" DOUBLE PRECISION,
    "f_fails_to_deliver_ratio_vs_peers" DOUBLE PRECISION,
    "f_fails_to_deliver_ratio_xs" DOUBLE PRECISION,
    "f_fails_to_deliver_chg_vs_peers" DOUBLE PRECISION,
    "f_fails_to_deliver_chg_xs" DOUBLE PRECISION,
    "f_ec_tone_vs_peers" DOUBLE PRECISION,
    "f_ec_tone_xs" DOUBLE PRECISION,
    "f_ec_tone_delta_vs_peers" DOUBLE PRECISION,
    "f_ec_tone_delta_xs" DOUBLE PRECISION,
    "f_ec_qa_gap_vs_peers" DOUBLE PRECISION,
    "f_ec_qa_gap_xs" DOUBLE PRECISION,
    "f_ec_uncertainty_vs_peers" DOUBLE PRECISION,
    "f_ec_uncertainty_xs" DOUBLE PRECISION,
    "f_ec_length_delta_vs_peers" DOUBLE PRECISION,
    "f_ec_length_delta_xs" DOUBLE PRECISION,
    "f_ec_vocab_novelty_vs_peers" DOUBLE PRECISION,
    "f_ec_vocab_novelty_xs" DOUBLE PRECISION,
    "f_ec_qa_tone_delta_vs_peers" DOUBLE PRECISION,
    "f_ec_qa_tone_delta_xs" DOUBLE PRECISION,
    "f_ec_prep_tone_delta_vs_peers" DOUBLE PRECISION,
    "f_ec_prep_tone_delta_xs" DOUBLE PRECISION,
    "f_ec_qa_coherence_mean_vs_peers" DOUBLE PRECISION,
    "f_ec_qa_coherence_mean_xs" DOUBLE PRECISION,
    "f_ec_qa_coherence_std_vs_peers" DOUBLE PRECISION,
    "f_ec_qa_coherence_std_xs" DOUBLE PRECISION,
    "f_ec_n_qa_vs_peers" DOUBLE PRECISION,
    "f_ec_n_qa_xs" DOUBLE PRECISION,
    "f_ec_qa_answer_ratio_vs_peers" DOUBLE PRECISION,
    "f_ec_qa_answer_ratio_xs" DOUBLE PRECISION,
    "f_ec_qa_answer_ratio_qq_vs_peers" DOUBLE PRECISION,
    "f_ec_qa_answer_ratio_qq_xs" DOUBLE PRECISION,
    "f_ec_qa_qq_sim_vs_peers" DOUBLE PRECISION,
    "f_ec_qa_qq_sim_xs" DOUBLE PRECISION,
    "f_ec_prep_qq_sim_vs_peers" DOUBLE PRECISION,
    "f_ec_prep_qq_sim_xs" DOUBLE PRECISION,
    "comp_value" DOUBLE PRECISION,
    "comp_value_rerating" DOUBLE PRECISION,
    "comp_quality" DOUBLE PRECISION,
    "comp_growth" DOUBLE PRECISION,
    "comp_distress" DOUBLE PRECISION,
    "comp_pension_risk" DOUBLE PRECISION,
    "comp_capital_allocation" DOUBLE PRECISION,
    "comp_shareholder_return" DOUBLE PRECISION,
    "comp_accounting_quality" DOUBLE PRECISION,
    "comp_ma_digestion" DOUBLE PRECISION,
    "comp_ai_capability" DOUBLE PRECISION,
    "comp_ai_opportunity" DOUBLE PRECISION,
    "comp_expectations" DOUBLE PRECISION,
    "comp_eps_beat" DOUBLE PRECISION,
    "comp_governance" DOUBLE PRECISION,
    "comp_workforce" DOUBLE PRECISION,
    "comp_insider" DOUBLE PRECISION,
    "comp_superinvestor" DOUBLE PRECISION,
    "comp_institutional" DOUBLE PRECISION,
    "comp_short_pressure" DOUBLE PRECISION,
    "comp_earnings_call" DOUBLE PRECISION,
    "comp_technical" DOUBLE PRECISION,
    "comp_bank_health" DOUBLE PRECISION,
    "comp_insurance_health" DOUBLE PRECISION,
    "comp_reit_health" DOUBLE PRECISION,
    "comp_energy_health" DOUBLE PRECISION,
    "beta_market" DOUBLE PRECISION,
    "beta_momentum" DOUBLE PRECISION,
    "beta_resvol" DOUBLE PRECISION,
    "beta_size" DOUBLE PRECISION,
    "beta_value" DOUBLE PRECISION,
    "beta_quality" DOUBLE PRECISION,
    "beta_oil" DOUBLE PRECISION,
    "beta_gold" DOUBLE PRECISION,
    "beta_USD/EUR" DOUBLE PRECISION,
    "beta_d_yield_10y" DOUBLE PRECISION,
    "beta_d_yield_curve" DOUBLE PRECISION,
    "beta_d_vix" DOUBLE PRECISION,
    "beta_d_breakeven_10y" DOUBLE PRECISION,
    "beta_sector" DOUBLE PRECISION,
    "beta_market_simple" DOUBLE PRECISION,
    "peers" TEXT,
    "sector" BIGINT,
    "industry_group" BIGINT,
    PRIMARY KEY ("ticker", "date", "target_horizon")
);

-- SKIPPED (no live schema and no previous DDL): cube_signal

-- SKIPPED (no live schema and no previous DDL): predictions

-- SKIPPED (no live schema and no previous DDL): predictions_latest

-- SKIPPED (no live schema and no previous DDL): trend_asset_returns

-- SKIPPED (no live schema and no previous DDL): strategy

-- [aggregate] fundamentals_check  (pk: run_date, run_id, check_name, ticker, field, period_key)
-- The fundamentals validator's APPEND-ONLY finding ledger (plan-5b decision 42). Written by
-- src/validate/; nothing else in that package mutates any table, and NOTHING HERE GATES -- the
-- nightly build of fundamentals_facts / fundamentals_history runs to completion whatever lands
-- in this table (decision 45, the SEC's own warn-over-reject precedent).
--
-- `run_date` IS IN THE KEY, so a re-run appends rather than overwrites: "did this check fire
-- yesterday?" stays answerable, and a check whose threshold moved leaves both verdicts on the
-- record. What survives across runs is `finding_id`, a deterministic hash of
-- (check_name, ticker, field, period_key), so a finding keeps its identity even though its rows
-- do not -- which is what makes differencing two comparable runs meaningful at all.
-- Deliberately NOT hashed from run_date, severity or observed: a threshold retune moves
-- severities in bulk (347 of them in one change) and must not re-key a finding.
--
-- `period_key` IS TEXT AND POLYMORPHIC, by the check's grain: the `as_of` for a history-grain
-- check, the `period_end` for a facts-grain one, '' for a ticker-level check
-- (filing_continuity), and 'start..end' for a series-grain one
-- (series_shape). ONE key column rather than three nullable ones, because a Postgres PK cannot
-- contain a NULL and a sentinel date would be a lie about which period the finding is about.
--
-- `run_id` IS IN THE KEY, and that was learned rather than designed. Without it the key is
-- (run_date, check_name, ticker, field, period_key), so TWO RUNS OF DIFFERENT SCOPE ON ONE DAY
-- collide on every ticker they share: a `-t MCD` run wrote 270 rows and a 54-ticker roster run
-- an hour later upserted over 269 of them, leaving the first run claiming 35 checks and one
-- surviving finding. Two runs that looked at different things have to be able to coexist.
--
-- `cluster_id` is a hash of (ticker, field) ALONE -- the DEFECT, of which every row here is one
-- witness. Not in the key and not unique by design: MCD capex trips NINE checks over dozens of
-- periods and that is ONE thing to fix, not nine jobs. `run_id` records which SCOPE produced
-- the row, so two runs can be differenced honestly -- see fundamentals_check_run below.
--
-- NOTHING IS SUBTRACTED ON THE WAY IN. Every finding of every run is written, including ones a
-- human has already settled, because a ledger that suppresses rows makes its own row count
-- meaningless: a drop would be ambiguous between "fixed" and "hidden". A wontfix is recorded in
-- fundamentals_check_status and applied when the report is RENDERED, never when the row is
-- written. That is what makes "fewer rows than the last comparable run" usable as proof.
--
-- The payload is decision 47's SELF-CONTAINED INVESTIGATION PACKET, and it is denormalised on
-- purpose. An identity-only row plus an on-demand join back to fundamentals_facts does not
-- work: a Tier-2/3 finding on a DERIVED value (a TTM, a derived_identity total, a computed
-- ratio) has NO single fact row to join to, so half the queue would arrive with an empty
-- provenance block and the reviewing agent would have to re-derive the number before it could
-- read the finding. `detail` is JSON, never prose -- an agent parsing English to decide what to
-- fix is the failure mode this rebuild exists to remove.

CREATE TABLE IF NOT EXISTS "fundamentals_check" (
    "run_date" DATE NOT NULL,
    "check_name" TEXT NOT NULL,
    "ticker" TEXT NOT NULL,
    "field" TEXT NOT NULL,
    "period_key" TEXT NOT NULL,
    "finding_id" TEXT,
    "tier" BIGINT,
    "severity" TEXT,
    "substrate" TEXT,
    "observed" DOUBLE PRECISION,
    "expected" DOUBLE PRECISION,
    "deviation" DOUBLE PRECISION,
    "as_of" DATE,
    "source_concept" TEXT,
    "resolution_method" TEXT,
    "roll_up_children" TEXT,
    "root_anchor" TEXT,
    "role_uri" TEXT,
    "accession_number" TEXT,
    "edgar_url" TEXT,
    "detail" TEXT,
    "run_id" TEXT NOT NULL,
    "cluster_id" TEXT,
    PRIMARY KEY ("run_date", "run_id", "check_name", "ticker", "field", "period_key")
);
CREATE INDEX IF NOT EXISTS ix_fundamentals_check_finding ON "fundamentals_check" ("finding_id");
CREATE INDEX IF NOT EXISTS ix_fundamentals_check_severity ON "fundamentals_check" ("severity");
CREATE INDEX IF NOT EXISTS ix_fundamentals_check_cluster ON "fundamentals_check" ("cluster_id");
CREATE INDEX IF NOT EXISTS ix_fundamentals_check_run_id ON "fundamentals_check" ("run_id");

-- [aggregate] fundamentals_check_run  (pk: run_id, check_name)
-- WHAT THE RUN LOOKED AT, and what each check did with it: one row per (run_id, check_name).
--
-- The validator's whole proposition is that a row-count drop in fundamentals_check PROVES a
-- fix worked. That proposition is FALSE unless the two runs looked at the same thing -- a
-- follow-up scoped to the one ticker somebody was fixing would report ~11,800 fewer findings
-- than a 54-ticker baseline and every one of them would read as a triumph. So the scope is
-- recorded here and hashed, and a run whose scope_hash differs is INCOMPARABLE: the report
-- omits the delta and says why rather than rendering a number that means nothing.
--
-- TWO HASHES, and one cannot do both jobs. `run_id` = 12 hex of (run_date, tickers, fields,
-- tiers) and IDENTIFIES a run; `scope_hash` = the same without the date and decides
-- COMPARABILITY. Including the date in the comparability key makes every run incomparable
-- with every other; excluding it makes today's run indistinguishable from last week's.
-- The roster NAME is stored but deliberately not hashed -- two runs covering the same
-- tickers are comparable whether or not someone renamed the roster in configs/ in between.
--
-- The scope columns REPEAT on every check row. Denormalised on purpose: it matches this
-- repo's flat-table convention and keeps "what did this run cover, and did anything abstain?"
-- a single read of ~35 rows. `scope_ticker_list` is the full JSON array beside its count,
-- because the count alone cannot answer "which 54?" -- the first question anyone
-- differencing two runs asks.
--
-- `abstained` and `over_ceiling` are STORED, not recomputed on read. They are the
-- check-health gate the report renders ABOVE its rankings, and a gate re-derived from a
-- ceiling that has since moved would answer a different question than the run asked. An
-- ABSTAINED check examined nothing, which is never a pass; a check over its own declared
-- ceiling has a threshold bug until proven otherwise and buries real findings under itself
-- (DQC_0118: "inconsistencies reported to filers can be overwhelming as many don't represent
-- real errors").

CREATE TABLE IF NOT EXISTS "fundamentals_check_run" (
    "run_id" TEXT NOT NULL,
    "run_date" DATE,
    "check_name" TEXT NOT NULL,
    "scope_hash" TEXT,
    "scope_roster" TEXT,
    "scope_tickers" BIGINT,
    "scope_ticker_list" TEXT,
    "scope_fields" TEXT,
    "scope_tiers" TEXT,
    "tier" BIGINT,
    "substrate" TEXT,
    "examined" BIGINT,
    "queued" BIGINT,
    "info" BIGINT,
    "ceiling" DOUBLE PRECISION,
    "abstained" BOOLEAN,
    "over_ceiling" BOOLEAN,
    PRIMARY KEY ("run_id", "check_name")
);
CREATE INDEX IF NOT EXISTS ix_fundamentals_check_run_scope ON "fundamentals_check_run" ("scope_hash");

-- [aggregate] fundamentals_check_status  (pk: cluster_id, check_name)
-- A HUMAN DECISION about one (ticker, field) defect. The only mutable state in the validator,
-- and the replacement for the deleted configs/fundamentals/fundamentals_check.json register.
--
-- `status` carries 'wontfix' AND NOTHING ELSE. `open`, `settled` and `reopened` are DERIVED
-- from the ledger -- open by default, settled when a cluster's queue findings are all either
-- gone or waived AND a fundamentals_check_fix row proves an intervention reduced them. A
-- stored `settled` that says so while the check still fires is exactly the suppression list
-- the JSON register was becoming, which is why the vocabulary here is one word long. A fully
-- waived cluster with no fix row behind it reads 'wontfix' -- tolerated, not solved.
--
-- `check_name` IS IN THE KEY and '' means the WHOLE cluster. Keyed on cluster_id alone a
-- waiver is all-or-nothing: MCD capex retains two benign `peer_ratio` findings on a
-- documented blind spot, and tolerating those at cluster grain would also silence the eight
-- other checks still live on the same defect. Per-check is the narrowest tolerance that can
-- be expressed, so it is the one stored -- and each entry expires on its OWN
-- findings_at_decision rather than on the cluster's total.
--
-- WAIVING EVERY CHECK STILL DOES NOT SETTLE A CLUSTER. Without that rule the suppression
-- list is simply reassembled one check at a time, which is the exact failure this schema
-- was redesigned to prevent.
--
-- `findings_at_decision` is what makes even a wontfix self-expiring: it records how big the
-- cluster was when somebody actually assessed it, and the cluster REOPENS automatically the
-- moment it grows past that. `register_coverage` -- the check that used to police the
-- register against silently becoming a suppression list -- is deleted, and this column plus
-- the report's never-omitted wontfix footer is what replaces its guarantee.
--
-- `note` is REQUIRED and must carry a QUANTIFIED cost -- a number, not an adjective. NEE's
-- $5.2bn understatement is a defensible wontfix precisely and only because the number is
-- written down.

CREATE TABLE IF NOT EXISTS "fundamentals_check_status" (
    "cluster_id" TEXT NOT NULL,
    "check_name" TEXT NOT NULL,
    "ticker" TEXT,
    "field" TEXT,
    "status" TEXT,
    "note" TEXT,
    "findings_at_decision" BIGINT,
    "decided_at" DATE,
    PRIMARY KEY ("cluster_id", "check_name")
);
CREATE INDEX IF NOT EXISTS ix_fundamentals_check_status_cluster ON "fundamentals_check_status" ("cluster_id");

-- [aggregate] fundamentals_check_fix  (pk: cluster_id, run_id_after)
-- AN INTERVENTION: what somebody actually did to a cluster, and what it measurably closed.
-- Append-only, and a DIFFERENT KIND OF THING from fundamentals_check_status above -- a fix
-- is an EVENT that happened, a waiver is a STATE that persists. Two fixes of one cluster are
-- two rows, because the second did not un-happen the first.
--
-- NO RENDERER MAY FILTER FINDINGS USING THIS TABLE. It records what was done; it never
-- subtracts a row from fundamentals_check, and a settlement computed from it never hides a
-- finding. That separation is the whole reason a fix is stored apart from a waiver, and it
-- is what keeps "fewer rows than the last comparable run" usable as proof. A test pins the
-- invariant directly: fundamentals_check row counts are byte-identical with and without any
-- of these rows present.
--
-- This table exists because a fix had NOWHERE TO BE RECORDED. Cluster 1c9a517eaa47 (MCD
-- capex) was fixed on 2026-08-25 and left no machine-readable trace anywhere: not in
-- _check_status (which accepts 'wontfix' and nothing else), not in the settled set (a strict
-- difference that a 55->4 drop does not satisfy), not in the rendered report (it fell off
-- the top-50). The only record was a commit sha.
--
-- `run_id_after` IS IN THE KEY because it is the run that PROVED the fix. Both runs must
-- share a `scope_hash` -- pinned here rather than looked up, so the proof survives even if
-- the runs are later pruned -- or the before/after counts are not a comparison at all. That
-- is the same test fundamentals_check_run exists to make.
--
-- `queued_before` / `queued_after` are the counts SETTLEMENT IS JUDGED ON: queue-severity
-- findings only, `info` excluded, because nothing reads an `info` finding as work. A row
-- with queued_after >= queued_before is still RECORDABLE -- a wrong-but-plausible value
-- corrected where no check was firing is a legitimate fix -- but it can never settle the
-- cluster. Permissive to record, strict to settle.
--
-- `layer` is a CLOSED four-term vocabulary (constants.FIX_LAYERS: check | catalogue |
-- extraction | rows) defined by what the edit DOES, never by which file it lives in --
-- otherwise every judgement call becomes an argument about directories. `check` = the check
-- was wrong; `catalogue` = the field specification was wrong; `extraction` = any code that
-- PRODUCES a value (xbrl_linkbase, build_history, periods); `rows` = the code was already
-- right and the stored data was stale. `root_cause` carries the precision; this is coarse
-- grouping, not a taxonomy.
--
-- `evidence` is JSON, NEVER PROSE -- the same rule fundamentals_check.detail follows, for
-- the same reason: an agent parsing English to decide what to trust is the failure mode this
-- whole subsystem exists to remove. Prose goes in `root_cause`. Required keys vary BY LAYER
-- (constants.FIX_EVIDENCE_KEYS): extraction/rows/catalogue must name `accessions`, while a
-- `check` fix has no filing at fault and cites the false-positive population it was measured
-- against instead (`examined`, `benign`).
--
-- `commit_sha` and `test_path` are BOTH REQUIRED and both verified on write: the sha against
-- `git rev-parse`, the path against the filesystem. An unreproducible fix record is worse
-- than a missing one in a table whose entire purpose is evidence.

CREATE TABLE IF NOT EXISTS "fundamentals_check_fix" (
    "cluster_id" TEXT NOT NULL,
    "run_id_after" TEXT NOT NULL,
    "run_id_before" TEXT,
    "scope_hash" TEXT,
    "ticker" TEXT,
    "field" TEXT,
    "findings_before" BIGINT,
    "findings_after" BIGINT,
    "queued_before" BIGINT,
    "queued_after" BIGINT,
    "layer" TEXT,
    "root_cause" TEXT,
    "evidence" TEXT,
    "commit_sha" TEXT,
    "test_path" TEXT,
    "decided_at" DATE,
    PRIMARY KEY ("cluster_id", "run_id_after")
);
CREATE INDEX IF NOT EXISTS ix_fundamentals_check_fix_ticker ON "fundamentals_check_fix" ("ticker");
CREATE INDEX IF NOT EXISTS ix_fundamentals_check_fix_decided_at ON "fundamentals_check_fix" ("decided_at");
